import { createContext, useCallback, useEffect, useMemo, useState } from "react";

const PreferencesContext = createContext(null);

const translations = {
  en: {
    "nav.home": "Home", "nav.aiTools": "AI Tools", "nav.studyGroups": "Study Groups", "nav.dashboard": "Dashboard",
    "nav.aiDoubtSolver": "AI Doubt Solver", "nav.aiSummarizer": "AI Summarizer", "nav.quizGenerator": "Quiz Generator", "nav.flashcards": "Flashcards", "nav.studyPlanner": "Study Planner",
    "nav.admin": "Admin", "sidebar.teacherVerification": "Teacher Verification", "sidebar.teacherVerifications": "Teacher Verifications",
    "sidebar.applyTeacher": "Apply as Teacher", "teacher.applyTitle": "Apply as Teacher", "teacher.applySubtitle": "Submit your qualifications for administrator review. Your account remains a student until approval.", "teacher.qualification": "Qualification", "teacher.institution": "Institution", "teacher.experience": "Years of experience", "teacher.specializations": "Subject specializations", "teacher.specializationsPlaceholder": "Mathematics, Physics", "teacher.commaSeparated": "Separate specializations with commas.", "teacher.document": "Qualification document", "teacher.documentHelp": "Private PDF, JPG or PNG; maximum 5 MB.", "teacher.submit": "Submit application", "teacher.resubmit": "Resubmit application", "teacher.submitted": "Teacher application submitted", "teacher.submitFailed": "Could not submit application", "teacher.loadFailed": "Could not load application status", "teacher.invalidFile": "Use a PDF, JPG or PNG file up to 5 MB", "teacher.documentRequired": "Upload your qualification document", "teacher.documentFailed": "Could not open document", "teacher.pendingTitle": "Teacher application pending", "teacher.pendingMessage": "Your application is awaiting administrator review.", "teacher.approvedTitle": "Teacher application approved", "teacher.approvedMessage": "Your teacher account and tools are now available.", "teacher.rejectedTitle": "Application rejected", "teacher.resubmitMessage": "Correct the details and submit a new application.", "teacher.viewDocument": "View submitted document", "teacher.openDashboard": "Open Teacher Dashboard", "teacher.studentsOnly": "Teacher applications are available to student accounts.",
    "language.english": "English",
    "language.tamil": "தமிழ்",
    "language.sinhala": "සිංහල",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.switchToLight": "Switch to light mode",
    "theme.switchToDark": "Switch to dark mode",
    "nav.exploreNotes": "Explore Notes",
    "nav.resources": "Resources",
    "nav.login": "Login",
    "nav.getStarted": "Get Started",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "nav.logout": "Logout",
    "auth.welcomeBack": "Welcome back",
    "auth.loginSubtitle": "Log in to continue your learning journey.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.login": "Login",
    "auth.noAccount": "Don't have an account?",
    "auth.signUp": "Sign up",
    "auth.emailRequired": "Email is required",
    "auth.passwordRequired": "Password is required",
    "auth.welcome": "Welcome back!",
    "auth.invalidLogin": "Invalid email or password",
    "auth.createTitle": "Create your account",
    "auth.createSubtitle": "Join students learning smarter with AI.",
    "auth.fullName": "Full Name",
    "auth.fullNamePlaceholder": "Enter your full name", "auth.emailPlaceholder": "Enter your email address", "auth.passwordPlaceholder": "Create a strong password", "auth.confirmPasswordPlaceholder": "Re-enter your password", "auth.showPassword": "Show password", "auth.hidePassword": "Hide password",
    "auth.confirmPassword": "Confirm Password",
    "auth.rolePrompt": "I am a",
    "auth.student": "Student",
    "auth.teacher": "Teacher",
    "auth.createAccount": "Create Account",
    "auth.haveAccount": "Already have an account?",
    "auth.accountCreated": "Account created successfully. You can now log in.",
    "auth.registrationFailed": "Registration failed",
    "academic.enterSubject": "Enter subject name", "academic.subjectRequired": "Please enter or select a subject.",
    "auth.nameRequired": "Enter your full name", "auth.strongPassword": "Use 8+ characters with uppercase, lowercase, number and special character", "auth.passwordMismatch": "Passwords do not match",
    "sidebar.studentVerification": "Student Verification", "sidebar.studentVerifications": "Student Verifications",
    "studentVerification.title": "Student Verification", "studentVerification.subtitle": "Verify your student status with a current school, college, or university document.",
    "studentVerification.loading": "Loading verification status...", "studentVerification.loadFailed": "Could not load your verification status.", "studentVerification.loadErrorTitle": "Verification status unavailable", "studentVerification.retry": "Try again",
    "studentVerification.uploadTitle": "Upload student proof", "studentVerification.uploadSubtitle": "Your document is reviewed privately by a Learnfy AI administrator.", "studentVerification.document": "Student ID or enrolment document", "studentVerification.documentHelp": "PDF, JPG, JPEG or PNG only. Maximum 5 MB.",
    "studentVerification.invalidFile": "Choose a PDF, JPG or PNG file up to 5 MB.", "studentVerification.documentRequired": "Choose a verification document.", "studentVerification.submit": "Submit for verification", "studentVerification.resubmit": "Resubmit document", "studentVerification.submitted": "Verification document submitted", "studentVerification.submitFailed": "Could not submit your document.",
    "studentVerification.statusTitle": "Verification status", "studentVerification.currentStatus": "Current status", "studentVerification.status.unverified": "Not verified", "studentVerification.status.rejected": "Needs attention", "studentVerification.privacy": "Your proof is stored privately and is available only to authorized administrators reviewing your request.",
    "studentVerification.pendingTitle": "Verification under review", "studentVerification.pendingMessage": "Your document was submitted successfully. An administrator is reviewing it.", "studentVerification.verifiedTitle": "Student Verified", "studentVerification.verifiedMessage": "Your student status has been approved. Your verified student badge is now active.",
    "studentVerification.rejectedTitle": "Verification needs attention", "studentVerification.rejectedMessage": "The submitted document could not be approved.", "studentVerification.resubmitMessage": "Review the reason above and submit a clear, current document.",
    "studentVerification.studentsOnlyTitle": "Student account required", "studentVerification.studentsOnlyMessage": "Student verification is available only to student accounts.", "studentVerification.backDashboard": "Back to Dashboard", "studentVerification.viewProfile": "View Profile",
    "home.badge": "Your smarter study companion",
    "home.heroOne": "Learn with clarity.",
    "home.heroTwo": "Grow with Learnfy AI.",
    "home.description": "Find notes, solve doubts with AI, practise quizzes, create study plans, and learn together.",
    "home.startFree": "Start Learning Free",
    "home.exploreNotes": "Explore Notes",
    "home.easy": "Easy to use",
    "home.studentFriendly": "Student friendly",
    "home.aiSupport": "AI-powered support",
    "home.allInOne": "Everything in one platform",
    "home.studySmarter": "Study smarter, not harder",
    "home.toolsDescription": "Useful tools that make learning clearer, more organised, and more engaging.",
    "home.featureDoubt": "AI Doubt Solver",
    "home.featureDoubtDesc": "Get simple, step-by-step explanations for difficult lessons in seconds.",
    "home.featureNotes": "Smart Notes Sharing",
    "home.featureNotesDesc": "Upload, discover, save, and download useful notes for every subject.",
    "home.featureGroups": "Study Groups",
    "home.featureGroupsDesc": "Learn with friends, discuss lessons, and stay motivated together.",
    "home.featureQuiz": "Quiz Generator",
    "home.featureQuizDesc": "Turn any lesson into practice questions and prepare confidently.",
    "home.featureProgress": "Personalized Progress",
    "home.featureProgressDesc": "Build a study plan, track progress, and focus on what matters most.",
    "home.featureSpace": "One Learning Space",
    "home.featureSpaceDesc": "Notes, AI tools, quizzes, groups, and planning in one calm workspace.",
    "home.journey": "Your learning journey starts here",
    "home.ready": "Ready to learn with confidence?",
    "home.ctaDescription": "Create your free Learnfy AI account and bring your notes, questions, practice, and progress together.",
    "home.createFree": "Create Free Account",
    "sidebar.dashboard": "Dashboard",
    "sidebar.notes": "Notes",
    "sidebar.resources": "Resources",
    "sidebar.uploadNote": "Upload Note",
    "sidebar.aiDoubtSolver": "AI Doubt Solver",
    "sidebar.aiSummarizer": "AI Summarizer",
    "sidebar.quizGenerator": "Quiz Generator",
    "sidebar.studyPlanner": "Study Planner",
    "sidebar.flashcards": "Flashcards",
    "sidebar.studyGroups": "Study Groups",
    "sidebar.notesResources": "Notes & Resources",
    "sidebar.teacherResources": "Teacher Resources",
    "sidebar.uploadMaterial": "Upload Material",
    "sidebar.aiAssistant": "AI Assistant",
    "sidebar.adminDashboard": "Admin Dashboard", "sidebar.adminUsers": "Users", "sidebar.adminSubjects": "Subjects", "sidebar.adminModeration": "Content Moderation", "sidebar.adminPayments": "Payments", "sidebar.adminAuditLogs": "Audit Logs", "admin.dashboardTitle": "Admin Dashboard", "admin.usersTitle": "User Management", "admin.moderationTitle": "Content Moderation", "admin.paymentsTitle": "Payments & Subscriptions", "admin.auditTitle": "Admin Audit Logs",
    "sidebar.allNotes": "All Notes",
    "sidebar.profile": "Profile",
    "sidebar.settings": "Settings",
    "settings.title": "Settings",
    "settings.appearanceLanguage": "Appearance & Language",
    "settings.theme": "Theme",
    "settings.language": "Display language",
    "settings.accountDetails": "Account Details",
    "settings.fullName": "Full Name",
    "settings.email": "Email",
    "settings.saveChanges": "Save Changes",
    "settings.nameUpdated": "Name updated",
    "settings.couldNotSave": "Could not save changes",
    "settings.notifications": "Notification Preferences",
    "settings.emailNotifications": "Email notifications",
    "settings.aiTips": "AI study tips & reminders",
    "settings.groupActivity": "Study group activity alerts",
    "settings.privacy": "Privacy & Security",
    "settings.currentPassword": "Current password",
    "settings.newPassword": "New password: uppercase, lowercase, number, special character",
    "settings.confirmPassword": "Confirm new password",
    "settings.changePassword": "Change Password",
    "settings.passwordMismatch": "New passwords do not match",
    "settings.passwordChanged": "Password changed",
    "settings.couldNotChangePassword": "Could not change password",
    "settings.logoutDevice": "Log out of this device",
    "settings.deleteAccount": "Delete Account",
    "settings.deleteDescription": "This permanently removes your account and related data.",
    "settings.confirmCurrentPassword": "Confirm with your current password",
    "settings.deleteMyAccount": "Delete My Account",
    "settings.enterPassword": "Enter your password first",
    "settings.deleteConfirm": "Delete your Learnfy account permanently?",
    "settings.accountDeleted": "Account deleted",
    "settings.couldNotDelete": "Could not delete account",
    "quiz.title": "AI Quiz Generator",
    "quiz.subtitle": "Generate MCQs, answer every question, and receive your marks with correct answers.",
    "quiz.subject": "Subject",
    "quiz.questionCount": "Number of Questions",
    "quiz.topic": "Topic",
    "quiz.topicPlaceholder": "e.g. Newton's Laws of Motion",
    "quiz.quizLanguage": "Quiz language",
    "quiz.difficulty": "Difficulty",
    "quiz.easy": "Easy",
    "quiz.medium": "Medium",
    "quiz.hard": "Hard",
    "quiz.generate": "Generate Quiz",
    "quiz.generating": "Generating quiz questions...",
    "quiz.enterTopic": "Enter a topic to generate quiz questions",
    "quiz.generateError": "Could not generate quiz",
    "quiz.answerAll": "Please answer all questions before submitting",
    "quiz.submit": "Submit Answers",
    "quiz.submitting": "Checking your answers...",
    "quiz.submitError": "Could not submit quiz answers",
    "quiz.result": "Quiz Result",
    "quiz.score": "Score",
    "quiz.percentage": "Percentage",
    "quiz.excellent": "Excellent work!",
    "quiz.good": "Good effort. Review the answers below.",
    "quiz.keepPractising": "Keep practising and try again.",
    "quiz.yourAnswer": "Your answer",
    "quiz.correctAnswer": "Correct answer",
    "quiz.notAnswered": "Not answered",
    "quiz.correct": "Correct",
    "quiz.incorrect": "Incorrect",
    "quiz.newQuiz": "Generate Another Quiz",
    "quiz.tryAgain": "Try Again",
    "groups.title": "Study Groups",
    "groups.create": "Create Group",
    "groups.admin": "Group Admin",
    "groups.members": "members",
    "groups.requests": "Requests",
    "groups.leave": "Leave",
    "groups.pending": "Pending",
    "groups.requestJoin": "Request to Join",
    "groups.delete": "Delete",
    "groups.discuss": "Discuss",
    "groups.noGroups": "No study groups yet — create the first one!",
    "nav.pricing": "Pricing",
    "sidebar.payments": "Premium & Payments",
    "payments.pricingTitle": "Choose how you learn",
    "payments.pricingSubtitle": "Start free or unlock the complete Learnfy AI experience with Premium.",
    "payments.bestValue": "Best value",
    "payments.days": "days",
    "payments.startFree": "Start free",
    "payments.choosePlan": "Choose plan",
    "payments.secureNotice": "Payments are securely processed by PayHere. Learnfy AI never receives your full card details.",
    "payments.loadError": "Could not load payment plans",
    "payments.checkoutError": "Could not start checkout",
    "payments.backToPlans": "Back to plans",
    "payments.orderSummary": "Order summary",
    "payments.daysAccess": "days of Premium access",
    "payments.cardOnStripe": "You will enter your card details on PayHere's secure payment page.",
    "payments.billingDetails": "Billing details",
    "payments.billingSubtitle": "PayHere securely processes your payment on the next page.",
    "payments.phone": "Phone number",
    "payments.address": "Address",
    "payments.city": "City",
    "payments.country": "Country",
    "payments.continueStripe": "Continue to PayHere",
    "payments.noCardStorage": "No card number or CVV is entered or stored on Learnfy AI.",
    "payments.missingOrder": "Payment order is missing",
    "payments.verifyError": "Could not verify payment status",
    "payments.successTitle": "Payment confirmed",
    "payments.pendingTitle": "Verifying payment",
    "payments.cancelledTitle": "Payment cancelled",
    "payments.failedTitle": "Payment unsuccessful",
    "payments.successMessage": "Your Premium access is now active.",
    "payments.pendingMessage": "We are waiting for PayHere's signed server confirmation. This page updates automatically.",
    "payments.cancelledMessage": "No payment was confirmed. You can return to pricing when ready.",
    "payments.failedMessage": "PayHere did not confirm this payment. Premium access was not activated.",
    "payments.orderId": "Order ID",
    "payments.amount": "Amount",
    "payments.viewSubscription": "View subscription",
    "payments.tryAgain": "Try again",
    "payments.premiumPayments": "Premium & Payments",
    "payments.manageSubtitle": "Review your Premium access and payment history.",
    "payments.currentPlan": "Current plan",
    "payments.activeUntil": "Active until",
    "payments.extendAccess": "Extend access",
    "payments.upgrade": "Upgrade to Premium",
    "payments.recentPayments": "Recent payments",
    "payments.date": "Date",
    "payments.plan": "Plan",
    "payments.status": "Status",
    "payments.noPayments": "No payments yet.",
    "common.cancel": "Cancel",
  },
  ta: {
    "nav.home": "முகப்பு", "nav.aiTools": "AI கருவிகள்", "nav.studyGroups": "படிப்புக் குழுக்கள்", "nav.dashboard": "முகப்புப்பலகை",
    "nav.aiDoubtSolver": "AI சந்தேகத் தீர்வாளர்", "nav.aiSummarizer": "AI சுருக்கி", "nav.quizGenerator": "வினாடி வினா உருவாக்கி", "nav.flashcards": "ஃபிளாஷ் கார்டுகள்", "nav.studyPlanner": "படிப்புத் திட்டம்",
    "nav.admin": "நிர்வாகம்", "sidebar.teacherVerification": "ஆசிரியர் சரிபார்ப்பு", "sidebar.teacherVerifications": "ஆசிரியர் சரிபார்ப்புகள்",
    "sidebar.applyTeacher": "ஆசிரியராக விண்ணப்பிக்கவும்", "teacher.applyTitle": "ஆசிரியராக விண்ணப்பிக்கவும்", "teacher.applySubtitle": "நிர்வாகி மதிப்பாய்வுக்காக உங்கள் தகுதிகளைச் சமர்ப்பிக்கவும். ஒப்புதல் வரை உங்கள் கணக்கு மாணவர் கணக்காகவே இருக்கும்.", "teacher.qualification": "தகுதி", "teacher.institution": "நிறுவனம்", "teacher.experience": "அனுபவ ஆண்டுகள்", "teacher.specializations": "பாட நிபுணத்துவங்கள்", "teacher.specializationsPlaceholder": "கணிதம், இயற்பியல்", "teacher.commaSeparated": "காற்புள்ளியால் பிரிக்கவும்.", "teacher.document": "தகுதி ஆவணம்", "teacher.documentHelp": "தனிப்பட்ட PDF, JPG அல்லது PNG; அதிகபட்சம் 5 MB.", "teacher.submit": "விண்ணப்பத்தைச் சமர்ப்பிக்கவும்", "teacher.resubmit": "மீண்டும் சமர்ப்பிக்கவும்", "teacher.submitted": "ஆசிரியர் விண்ணப்பம் சமர்ப்பிக்கப்பட்டது", "teacher.submitFailed": "விண்ணப்பத்தைச் சமர்ப்பிக்க முடியவில்லை", "teacher.loadFailed": "விண்ணப்ப நிலையை ஏற்ற முடியவில்லை", "teacher.invalidFile": "5 MB வரை PDF, JPG அல்லது PNG கோப்பைப் பயன்படுத்தவும்", "teacher.documentRequired": "தகுதி ஆவணத்தைப் பதிவேற்றவும்", "teacher.documentFailed": "ஆவணத்தைத் திறக்க முடியவில்லை", "teacher.pendingTitle": "ஆசிரியர் விண்ணப்பம் நிலுவையில் உள்ளது", "teacher.pendingMessage": "உங்கள் விண்ணப்பம் நிர்வாகி மதிப்பாய்வுக்காக காத்திருக்கிறது.", "teacher.approvedTitle": "ஆசிரியர் விண்ணப்பம் அங்கீகரிக்கப்பட்டது", "teacher.approvedMessage": "உங்கள் ஆசிரியர் கணக்கும் கருவிகளும் இப்போது கிடைக்கின்றன.", "teacher.rejectedTitle": "விண்ணப்பம் நிராகரிக்கப்பட்டது", "teacher.resubmitMessage": "விவரங்களைச் சரிசெய்து மீண்டும் சமர்ப்பிக்கவும்.", "teacher.viewDocument": "சமர்ப்பித்த ஆவணத்தைப் பார்க்கவும்", "teacher.openDashboard": "ஆசிரியர் டாஷ்போர்டைத் திறக்கவும்", "teacher.studentsOnly": "மாணவர் கணக்குகளுக்கு ஆசிரியர் விண்ணப்பம் கிடைக்கும்.",
    "language.english": "English",
    "language.tamil": "தமிழ்",
    "language.sinhala": "සිංහල",
    "theme.light": "ஒளி",
    "theme.dark": "இருள்",
    "theme.switchToLight": "ஒளி முறைக்கு மாற்று",
    "theme.switchToDark": "இருள் முறைக்கு மாற்று",
    "nav.exploreNotes": "குறிப்புகளைப் பார்வையிடு",
    "nav.resources": "வளங்கள்",
    "nav.login": "உள்நுழைவு",
    "nav.getStarted": "தொடங்குங்கள்",
    "nav.profile": "சுயவிவரம்",
    "nav.settings": "அமைப்புகள்",
    "nav.logout": "வெளியேறு",
    "auth.welcomeBack": "மீண்டும் வரவேற்கிறோம்",
    "auth.loginSubtitle": "உங்கள் கற்றலைத் தொடர உள்நுழையுங்கள்.",
    "auth.email": "மின்னஞ்சல்",
    "auth.password": "கடவுச்சொல்",
    "auth.forgotPassword": "கடவுச்சொல் மறந்துவிட்டதா?",
    "auth.login": "உள்நுழைவு",
    "auth.noAccount": "கணக்கு இல்லையா?",
    "auth.signUp": "பதிவு செய்க",
    "auth.emailRequired": "மின்னஞ்சல் அவசியம்",
    "auth.passwordRequired": "கடவுச்சொல் அவசியம்",
    "auth.welcome": "மீண்டும் வரவேற்கிறோம்!",
    "auth.invalidLogin": "மின்னஞ்சல் அல்லது கடவுச்சொல் தவறானது",
    "auth.createTitle": "உங்கள் கணக்கை உருவாக்குங்கள்",
    "auth.createSubtitle": "AI உடன் புத்திசாலித்தனமாகக் கற்க இணைந்திடுங்கள்.",
    "auth.fullName": "முழுப் பெயர்",
    "auth.fullNamePlaceholder": "உங்கள் முழுப் பெயரை உள்ளிடவும்", "auth.emailPlaceholder": "உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும்", "auth.passwordPlaceholder": "வலுவான கடவுச்சொல்லை உருவாக்கவும்", "auth.confirmPasswordPlaceholder": "உங்கள் கடவுச்சொல்லை மீண்டும் உள்ளிடவும்", "auth.showPassword": "கடவுச்சொல்லைக் காட்டு", "auth.hidePassword": "கடவுச்சொல்லை மறை",
    "auth.confirmPassword": "கடவுச்சொல்லை உறுதிப்படுத்து",
    "auth.rolePrompt": "நான் ஒரு",
    "auth.student": "மாணவர்",
    "auth.teacher": "ஆசிரியர்",
    "auth.createAccount": "கணக்கை உருவாக்கு",
    "auth.haveAccount": "ஏற்கனவே கணக்கு உள்ளதா?",
    "auth.accountCreated": "கணக்கு உருவாக்கப்பட்டது! Learnfy AI-க்கு வரவேற்கிறோம்.",
    "auth.registrationFailed": "பதிவு செய்ய முடியவில்லை",
    "academic.enterSubject": "பாடத்தின் பெயரை உள்ளிடவும்", "academic.subjectRequired": "ஒரு பாடத்தை உள்ளிடவும் அல்லது தேர்ந்தெடுக்கவும்.",
    "auth.nameRequired": "முழுப் பெயரை உள்ளிடவும்", "auth.strongPassword": "பெரிய எழுத்து, சிறிய எழுத்து, எண் மற்றும் சிறப்பு குறியீட்டுடன் 8+ எழுத்துகளைப் பயன்படுத்தவும்", "auth.passwordMismatch": "கடவுச்சொற்கள் பொருந்தவில்லை",
    "sidebar.studentVerification": "மாணவர் சரிபார்ப்பு", "sidebar.studentVerifications": "மாணவர் சரிபார்ப்புகள்",
    "studentVerification.title": "மாணவர் சரிபார்ப்பு", "studentVerification.subtitle": "தற்போதைய பாடசாலை, கல்லூரி அல்லது பல்கலைக்கழக ஆவணத்தின் மூலம் உங்கள் மாணவர் நிலையை உறுதிப்படுத்துங்கள்.",
    "studentVerification.loading": "சரிபார்ப்பு நிலை ஏற்றப்படுகிறது...", "studentVerification.loadFailed": "உங்கள் சரிபார்ப்பு நிலையை ஏற்ற முடியவில்லை.", "studentVerification.loadErrorTitle": "சரிபார்ப்பு நிலை கிடைக்கவில்லை", "studentVerification.retry": "மீண்டும் முயற்சிக்கவும்",
    "studentVerification.uploadTitle": "மாணவர் சான்றை பதிவேற்றவும்", "studentVerification.uploadSubtitle": "உங்கள் ஆவணம் Learnfy AI நிர்வாகியால் தனிப்பட்ட முறையில் பரிசீலிக்கப்படும்.", "studentVerification.document": "மாணவர் அடையாள அட்டை அல்லது சேர்க்கை ஆவணம்", "studentVerification.documentHelp": "PDF, JPG, JPEG அல்லது PNG மட்டும். அதிகபட்சம் 5 MB.",
    "studentVerification.invalidFile": "5 MB வரை உள்ள PDF, JPG அல்லது PNG கோப்பைத் தேர்ந்தெடுக்கவும்.", "studentVerification.documentRequired": "சரிபார்ப்பு ஆவணத்தைத் தேர்ந்தெடுக்கவும்.", "studentVerification.submit": "சரிபார்ப்புக்கு சமர்ப்பிக்கவும்", "studentVerification.resubmit": "ஆவணத்தை மீண்டும் சமர்ப்பிக்கவும்", "studentVerification.submitted": "சரிபார்ப்பு ஆவணம் சமர்ப்பிக்கப்பட்டது", "studentVerification.submitFailed": "உங்கள் ஆவணத்தை சமர்ப்பிக்க முடியவில்லை.",
    "studentVerification.statusTitle": "சரிபார்ப்பு நிலை", "studentVerification.currentStatus": "தற்போதைய நிலை", "studentVerification.status.unverified": "சரிபார்க்கப்படவில்லை", "studentVerification.status.rejected": "கவனம் தேவை", "studentVerification.privacy": "உங்கள் சான்று தனிப்பட்ட முறையில் சேமிக்கப்பட்டு, அங்கீகரிக்கப்பட்ட நிர்வாகிகளுக்கு மட்டுமே கிடைக்கும்.",
    "studentVerification.pendingTitle": "சரிபார்ப்பு பரிசீலனையில் உள்ளது", "studentVerification.pendingMessage": "உங்கள் ஆவணம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது. நிர்வாகி அதைப் பரிசீலிக்கிறார்.", "studentVerification.verifiedTitle": "மாணவர் சரிபார்க்கப்பட்டார்", "studentVerification.verifiedMessage": "உங்கள் மாணவர் நிலை அங்கீகரிக்கப்பட்டது. சரிபார்க்கப்பட்ட மாணவர் அடையாளம் இப்போது செயலில் உள்ளது.",
    "studentVerification.rejectedTitle": "சரிபார்ப்புக்கு கவனம் தேவை", "studentVerification.rejectedMessage": "சமர்ப்பிக்கப்பட்ட ஆவணத்தை அங்கீகரிக்க முடியவில்லை.", "studentVerification.resubmitMessage": "மேலே உள்ள காரணத்தைப் பார்த்து தெளிவான, தற்போதைய ஆவணத்தை சமர்ப்பிக்கவும்.",
    "studentVerification.studentsOnlyTitle": "மாணவர் கணக்கு தேவை", "studentVerification.studentsOnlyMessage": "மாணவர் சரிபார்ப்பு மாணவர் கணக்குகளுக்கு மட்டுமே கிடைக்கும்.", "studentVerification.backDashboard": "டாஷ்போர்டுக்குத் திரும்பு", "studentVerification.viewProfile": "சுயவிவரத்தைப் பார்க்கவும்",
    "home.badge": "உங்கள் புத்திசாலியான படிப்பு துணை",
    "home.heroOne": "தெளிவாகக் கற்றுக்கொள்ளுங்கள்.",
    "home.heroTwo": "Learnfy AI உடன் வளருங்கள்.",
    "home.description": "குறிப்புகளைப் பெற்று, AI மூலம் சந்தேகங்களைத் தீர்த்து, வினாடி வினா பயிற்சி செய்து, படிப்புத் திட்டங்களை உருவாக்குங்கள்.",
    "home.startFree": "இலவசமாகக் கற்கத் தொடங்கு",
    "home.exploreNotes": "குறிப்புகளைப் பார்வையிடு",
    "home.easy": "பயன்படுத்த எளிது",
    "home.studentFriendly": "மாணவர் நட்பு",
    "home.aiSupport": "AI ஆதரவு",
    "home.allInOne": "அனைத்தும் ஒரே தளத்தில்",
    "home.studySmarter": "கடினமாக அல்ல, புத்திசாலித்தனமாகப் படியுங்கள்",
    "home.toolsDescription": "கற்றலைத் தெளிவாகவும் ஒழுங்காகவும் சுவாரசியமாகவும் மாற்றும் பயனுள்ள கருவிகள்.",
    "home.featureDoubt": "AI சந்தேக தீர்வு",
    "home.featureDoubtDesc": "கடினமான பாடங்களுக்கு எளிய படிப்படியான விளக்கங்களை உடனே பெறுங்கள்.",
    "home.featureNotes": "புத்திசாலியான குறிப்புப் பகிர்வு",
    "home.featureNotesDesc": "ஒவ்வொரு பாடத்திற்குமான குறிப்புகளைப் பதிவேற்றி, தேடி, சேமித்து, பதிவிறக்குங்கள்.",
    "home.featureGroups": "படிப்புக் குழுக்கள்",
    "home.featureGroupsDesc": "நண்பர்களுடன் கற்று, பாடங்களைப் பற்றி விவாதித்து, ஊக்கத்துடன் இருங்கள்.",
    "home.featureQuiz": "வினாடி வினா உருவாக்கி",
    "home.featureQuizDesc": "எந்தப் பாடத்தையும் பயிற்சி வினாக்களாக மாற்றி நம்பிக்கையுடன் தயாராகுங்கள்.",
    "home.featureProgress": "தனிப்பயன் முன்னேற்றம்",
    "home.featureProgressDesc": "படிப்புத் திட்டம் அமைத்து, முன்னேற்றத்தைக் கண்காணித்து, முக்கியவற்றில் கவனம் செலுத்துங்கள்.",
    "home.featureSpace": "ஒரே கற்றல் இடம்",
    "home.featureSpaceDesc": "குறிப்புகள், AI கருவிகள், வினாக்கள், குழுக்கள் மற்றும் திட்டங்கள் அனைத்தும் ஒரே இடத்தில்.",
    "home.journey": "உங்கள் கற்றல் பயணம் இங்கே தொடங்குகிறது",
    "home.ready": "நம்பிக்கையுடன் கற்கத் தயாரா?",
    "home.ctaDescription": "இலவச Learnfy AI கணக்கை உருவாக்கி, குறிப்புகள், கேள்விகள், பயிற்சி மற்றும் முன்னேற்றத்தை ஒன்றிணையுங்கள்.",
    "home.createFree": "இலவச கணக்கை உருவாக்கு",
    "sidebar.dashboard": "முகப்புப்பலகை",
    "sidebar.notes": "குறிப்புகள்",
    "sidebar.resources": "வளங்கள்",
    "sidebar.uploadNote": "குறிப்பைப் பதிவேற்று",
    "sidebar.aiDoubtSolver": "AI சந்தேக தீர்வு",
    "sidebar.aiSummarizer": "AI சுருக்கம்",
    "sidebar.quizGenerator": "வினாடி வினா",
    "sidebar.studyPlanner": "படிப்புத் திட்டம்",
    "sidebar.flashcards": "ஃப்ளாஷ் கார்டுகள்",
    "sidebar.studyGroups": "படிப்புக் குழுக்கள்",
    "sidebar.notesResources": "குறிப்புகள் மற்றும் வளங்கள்",
    "sidebar.teacherResources": "ஆசிரியர் வளங்கள்",
    "sidebar.uploadMaterial": "பாடப் பொருளைப் பதிவேற்று",
    "sidebar.aiAssistant": "AI உதவியாளர்",
    "sidebar.adminDashboard": "நிர்வாக முகப்புப்பலகை", "sidebar.adminUsers": "பயனர்கள்", "sidebar.adminSubjects": "பாடங்கள்", "sidebar.adminModeration": "உள்ளடக்கக் கண்காணிப்பு", "sidebar.adminPayments": "கட்டணங்கள்", "sidebar.adminAuditLogs": "தணிக்கை பதிவுகள்", "admin.dashboardTitle": "நிர்வாக முகப்புப்பலகை", "admin.usersTitle": "பயனர் மேலாண்மை", "admin.moderationTitle": "உள்ளடக்கக் கண்காணிப்பு", "admin.paymentsTitle": "கட்டணங்கள் மற்றும் சந்தாக்கள்", "admin.auditTitle": "நிர்வாக தணிக்கை பதிவுகள்",
    "sidebar.allNotes": "அனைத்து குறிப்புகள்",
    "sidebar.profile": "சுயவிவரம்",
    "sidebar.settings": "அமைப்புகள்",
    "settings.title": "அமைப்புகள்",
    "settings.appearanceLanguage": "தோற்றம் மற்றும் மொழி",
    "settings.theme": "தீம்",
    "settings.language": "காட்சி மொழி",
    "settings.accountDetails": "கணக்கு விவரங்கள்",
    "settings.fullName": "முழுப் பெயர்",
    "settings.email": "மின்னஞ்சல்",
    "settings.saveChanges": "மாற்றங்களைச் சேமி",
    "settings.nameUpdated": "பெயர் புதுப்பிக்கப்பட்டது",
    "settings.couldNotSave": "மாற்றங்களைச் சேமிக்க முடியவில்லை",
    "settings.notifications": "அறிவிப்பு விருப்பங்கள்",
    "settings.emailNotifications": "மின்னஞ்சல் அறிவிப்புகள்",
    "settings.aiTips": "AI படிப்பு குறிப்புகள் மற்றும் நினைவூட்டல்கள்",
    "settings.groupActivity": "படிப்புக் குழு செயல்பாட்டு அறிவிப்புகள்",
    "settings.privacy": "தனியுரிமை மற்றும் பாதுகாப்பு",
    "settings.currentPassword": "தற்போதைய கடவுச்சொல்",
    "settings.newPassword": "புதிய கடவுச்சொல்: பெரிய எழுத்து, சிறிய எழுத்து, எண், சிறப்புக் குறி",
    "settings.confirmPassword": "புதிய கடவுச்சொல்லை உறுதிப்படுத்து",
    "settings.changePassword": "கடவுச்சொல்லை மாற்று",
    "settings.passwordMismatch": "புதிய கடவுச்சொற்கள் பொருந்தவில்லை",
    "settings.passwordChanged": "கடவுச்சொல் மாற்றப்பட்டது",
    "settings.couldNotChangePassword": "கடவுச்சொல்லை மாற்ற முடியவில்லை",
    "settings.logoutDevice": "இந்த சாதனத்திலிருந்து வெளியேறு",
    "settings.deleteAccount": "கணக்கை நீக்கு",
    "settings.deleteDescription": "இது உங்கள் கணக்கையும் தொடர்புடைய தரவையும் நிரந்தரமாக நீக்கும்.",
    "settings.confirmCurrentPassword": "தற்போதைய கடவுச்சொல்லால் உறுதிப்படுத்து",
    "settings.deleteMyAccount": "எனது கணக்கை நீக்கு",
    "settings.enterPassword": "முதலில் கடவுச்சொல்லை உள்ளிடுங்கள்",
    "settings.deleteConfirm": "Learnfy கணக்கை நிரந்தரமாக நீக்க வேண்டுமா?",
    "settings.accountDeleted": "கணக்கு நீக்கப்பட்டது",
    "settings.couldNotDelete": "கணக்கை நீக்க முடியவில்லை",
    "quiz.title": "AI வினாடி வினா உருவாக்கி",
    "quiz.subtitle": "வினாக்களை உருவாக்கி, அனைத்திற்கும் பதிலளித்து, சரியான பதில்களுடன் மதிப்பெண் பெறுங்கள்.",
    "quiz.subject": "பாடம்",
    "quiz.questionCount": "வினாக்களின் எண்ணிக்கை",
    "quiz.topic": "தலைப்பு",
    "quiz.topicPlaceholder": "உதா: நியூட்டனின் இயக்க விதிகள்",
    "quiz.quizLanguage": "வினா மொழி",
    "quiz.difficulty": "சிரம நிலை",
    "quiz.easy": "எளிது",
    "quiz.medium": "நடுத்தரம்",
    "quiz.hard": "கடினம்",
    "quiz.generate": "வினாடி வினா உருவாக்கு",
    "quiz.generating": "வினாக்கள் உருவாக்கப்படுகின்றன...",
    "quiz.enterTopic": "வினாக்களை உருவாக்க ஒரு தலைப்பை உள்ளிடுங்கள்",
    "quiz.generateError": "வினாடி வினாவை உருவாக்க முடியவில்லை",
    "quiz.answerAll": "சமர்ப்பிப்பதற்கு முன் எல்லா வினாக்களுக்கும் பதிலளிக்கவும்",
    "quiz.submit": "பதில்களைச் சமர்ப்பி",
    "quiz.submitting": "பதில்கள் சரிபார்க்கப்படுகின்றன...",
    "quiz.submitError": "பதில்களைச் சமர்ப்பிக்க முடியவில்லை",
    "quiz.result": "வினாடி வினா முடிவு",
    "quiz.score": "மதிப்பெண்",
    "quiz.percentage": "சதவீதம்",
    "quiz.excellent": "மிகச் சிறப்பு!",
    "quiz.good": "நல்ல முயற்சி. கீழே உள்ள பதில்களைப் பாருங்கள்.",
    "quiz.keepPractising": "தொடர்ந்து பயிற்சி செய்து மீண்டும் முயற்சிக்கவும்.",
    "quiz.yourAnswer": "உங்கள் பதில்",
    "quiz.correctAnswer": "சரியான பதில்",
    "quiz.notAnswered": "பதிலளிக்கப்படவில்லை",
    "quiz.correct": "சரி",
    "quiz.incorrect": "தவறு",
    "quiz.newQuiz": "மற்றொரு வினாடி வினா",
    "quiz.tryAgain": "மீண்டும் முயற்சி",
    "groups.title": "படிப்புக் குழுக்கள்",
    "groups.create": "குழுவை உருவாக்கு",
    "groups.admin": "குழு நிர்வாகி",
    "groups.members": "உறுப்பினர்கள்",
    "groups.requests": "கோரிக்கைகள்",
    "groups.leave": "வெளியேறு",
    "groups.pending": "நிலுவையில்",
    "groups.requestJoin": "சேர கோரிக்கை",
    "groups.delete": "நீக்கு",
    "groups.discuss": "கலந்துரையாடு",
    "groups.noGroups": "படிப்புக் குழுக்கள் இல்லை — முதல் குழுவை உருவாக்குங்கள்!",
    "nav.pricing": "விலைகள்",
    "sidebar.payments": "பிரீமியம் & கட்டணங்கள்",
    "payments.pricingTitle": "உங்கள் கற்றல் திட்டத்தைத் தேர்ந்தெடுக்கவும்",
    "payments.pricingSubtitle": "இலவசமாகத் தொடங்குங்கள் அல்லது பிரீமியம் மூலம் முழு Learnfy AI அனுபவத்தைப் பெறுங்கள்.",
    "payments.bestValue": "சிறந்த மதிப்பு",
    "payments.days": "நாட்கள்",
    "payments.startFree": "இலவசமாகத் தொடங்கு",
    "payments.choosePlan": "திட்டத்தைத் தேர்வு செய்",
    "payments.secureNotice": "கட்டணங்கள் PayHere மூலம் பாதுகாப்பாகச் செயலாக்கப்படுகின்றன. Learnfy AI உங்கள் முழு அட்டை விவரங்களைப் பெறாது.",
    "payments.loadError": "கட்டணத் திட்டங்களை ஏற்ற முடியவில்லை",
    "payments.checkoutError": "கட்டணத்தைத் தொடங்க முடியவில்லை",
    "payments.backToPlans": "திட்டங்களுக்குத் திரும்பு",
    "payments.orderSummary": "ஆர்டர் சுருக்கம்",
    "payments.daysAccess": "நாட்கள் பிரீமியம் அணுகல்",
    "payments.cardOnStripe": "PayHere பாதுகாப்பான பக்கத்தில் உங்கள் அட்டை விவரங்களை உள்ளிடுவீர்கள்.",
    "payments.billingDetails": "கட்டண விவரங்கள்",
    "payments.billingSubtitle": "PayHere பாதுகாப்பாக உங்கள் கட்டணத்தைச் செயலாக்கும்.",
    "payments.phone": "தொலைபேசி எண்",
    "payments.address": "முகவரி",
    "payments.city": "நகரம்",
    "payments.country": "நாடு",
    "payments.continueStripe": "PayHereக்குத் தொடரவும்",
    "payments.noCardStorage": "அட்டை எண் அல்லது CVV Learnfy AI இல் உள்ளிடப்படவோ சேமிக்கப்படவோ இல்லை.",
    "payments.missingOrder": "கட்டண ஆர்டர் இல்லை",
    "payments.verifyError": "கட்டண நிலையைச் சரிபார்க்க முடியவில்லை",
    "payments.successTitle": "கட்டணம் உறுதிப்படுத்தப்பட்டது",
    "payments.pendingTitle": "கட்டணம் சரிபார்க்கப்படுகிறது",
    "payments.cancelledTitle": "கட்டணம் ரத்து செய்யப்பட்டது",
    "payments.failedTitle": "கட்டணம் வெற்றியளிக்கவில்லை",
    "payments.successMessage": "உங்கள் பிரீமியம் அணுகல் இப்போது செயலில் உள்ளது.",
    "payments.pendingMessage": "PayHere இன் பாதுகாப்பான உறுதிப்படுத்தலுக்காக காத்திருக்கிறோம்.",
    "payments.cancelledMessage": "கட்டணம் உறுதிப்படுத்தப்படவில்லை. பின்னர் மீண்டும் முயற்சிக்கலாம்.",
    "payments.failedMessage": "PayHere இந்தக் கட்டணத்தை உறுதிப்படுத்தவில்லை.",
    "payments.orderId": "ஆர்டர் எண்",
    "payments.amount": "தொகை",
    "payments.viewSubscription": "சந்தாவைப் பார்க்கவும்",
    "payments.tryAgain": "மீண்டும் முயற்சி செய்",
    "payments.premiumPayments": "பிரீமியம் & கட்டணங்கள்",
    "payments.manageSubtitle": "உங்கள் பிரீமியம் அணுகலையும் கட்டண வரலாற்றையும் பார்க்கவும்.",
    "payments.currentPlan": "தற்போதைய திட்டம்",
    "payments.activeUntil": "செயலில் இருக்கும் நாள்",
    "payments.extendAccess": "அணுகலை நீட்டிக்கவும்",
    "payments.upgrade": "பிரீமியத்திற்கு மேம்படுத்து",
    "payments.recentPayments": "சமீபத்திய கட்டணங்கள்",
    "payments.date": "தேதி",
    "payments.plan": "திட்டம்",
    "payments.status": "நிலை",
    "payments.noPayments": "இதுவரை கட்டணங்கள் இல்லை.",
    "common.cancel": "ரத்து செய்",
  },
  si: {
    "nav.home": "මුල් පිටුව", "nav.aiTools": "AI මෙවලම්", "nav.studyGroups": "අධ්‍යයන කණ්ඩායම්", "nav.dashboard": "උපකරණ පුවරුව",
    "nav.aiDoubtSolver": "AI ගැටලු විසඳුම", "nav.aiSummarizer": "AI සාරාංශකය", "nav.quizGenerator": "ප්‍රශ්නාවලි සාදකය", "nav.flashcards": "ෆ්ලෑෂ් කාඩ්පත්", "nav.studyPlanner": "අධ්‍යයන සැලසුම්කරු",
    "nav.admin": "පරිපාලක", "sidebar.teacherVerification": "ගුරු සත්‍යාපනය", "sidebar.teacherVerifications": "ගුරු සත්‍යාපන",
    "sidebar.applyTeacher": "ගුරුවරයෙකු ලෙස අයදුම් කරන්න", "teacher.applyTitle": "ගුරුවරයෙකු ලෙස අයදුම් කරන්න", "teacher.applySubtitle": "පරිපාලක සමාලෝචනය සඳහා ඔබේ සුදුසුකම් ඉදිරිපත් කරන්න. අනුමැතිය ලැබෙන තෙක් ගිණුම ශිෂ්‍ය ගිණුමක් ලෙස පවතී.", "teacher.qualification": "සුදුසුකම", "teacher.institution": "ආයතනය", "teacher.experience": "පළපුරුදු වසර", "teacher.specializations": "විෂය විශේෂඥතා", "teacher.specializationsPlaceholder": "ගණිතය, භෞතික විද්‍යාව", "teacher.commaSeparated": "කොමා මඟින් වෙන් කරන්න.", "teacher.document": "සුදුසුකම් ලේඛනය", "teacher.documentHelp": "පුද්ගලික PDF, JPG හෝ PNG; උපරිම 5 MB.", "teacher.submit": "අයදුම්පත ඉදිරිපත් කරන්න", "teacher.resubmit": "නැවත ඉදිරිපත් කරන්න", "teacher.submitted": "ගුරු අයදුම්පත ඉදිරිපත් කරන ලදී", "teacher.submitFailed": "අයදුම්පත ඉදිරිපත් කළ නොහැක", "teacher.loadFailed": "අයදුම් තත්ත්වය පූරණය කළ නොහැක", "teacher.invalidFile": "5 MB දක්වා PDF, JPG හෝ PNG ගොනුවක් භාවිත කරන්න", "teacher.documentRequired": "සුදුසුකම් ලේඛනය උඩුගත කරන්න", "teacher.documentFailed": "ලේඛනය විවෘත කළ නොහැක", "teacher.pendingTitle": "ගුරු අයදුම්පත පොරොත්තුවේ", "teacher.pendingMessage": "ඔබේ අයදුම්පත පරිපාලක සමාලෝචනය සඳහා බලා සිටී.", "teacher.approvedTitle": "ගුරු අයදුම්පත අනුමතයි", "teacher.approvedMessage": "ඔබේ ගුරු ගිණුම සහ මෙවලම් දැන් ලබා ගත හැක.", "teacher.rejectedTitle": "අයදුම්පත ප්‍රතික්ෂේපයි", "teacher.resubmitMessage": "විස්තර නිවැරදි කර නැවත ඉදිරිපත් කරන්න.", "teacher.viewDocument": "ඉදිරිපත් කළ ලේඛනය බලන්න", "teacher.openDashboard": "ගුරු උපකරණ පුවරුව විවෘත කරන්න", "teacher.studentsOnly": "ගුරු අයදුම් ශිෂ්‍ය ගිණුම් සඳහා ලබා ගත හැක.",
    "language.english": "English",
    "language.tamil": "தமிழ்",
    "language.sinhala": "සිංහල",
    "theme.light": "ආලෝක",
    "theme.dark": "අඳුරු",
    "theme.switchToLight": "ආලෝක ප්‍රකාරයට මාරු වන්න",
    "theme.switchToDark": "අඳුරු ප්‍රකාරයට මාරු වන්න",
    "nav.exploreNotes": "සටහන් බලන්න",
    "nav.resources": "සම්පත්",
    "nav.login": "පිවිසෙන්න",
    "nav.getStarted": "ආරම්භ කරන්න",
    "nav.profile": "පැතිකඩ",
    "nav.settings": "සැකසුම්",
    "nav.logout": "ඉවත් වන්න",
    "auth.welcomeBack": "නැවත සාදරයෙන් පිළිගනිමු",
    "auth.loginSubtitle": "ඔබගේ ඉගෙනීම දිගටම කරගෙන යාමට පිවිසෙන්න.",
    "auth.email": "විද්‍යුත් තැපෑල",
    "auth.password": "මුරපදය",
    "auth.forgotPassword": "මුරපදය අමතකද?",
    "auth.login": "පිවිසෙන්න",
    "auth.noAccount": "ගිණුමක් නැද්ද?",
    "auth.signUp": "ලියාපදිංචි වන්න",
    "auth.emailRequired": "විද්‍යුත් තැපෑල අවශ්‍යයි",
    "auth.passwordRequired": "මුරපදය අවශ්‍යයි",
    "auth.welcome": "නැවත සාදරයෙන් පිළිගනිමු!",
    "auth.invalidLogin": "විද්‍යුත් තැපෑල හෝ මුරපදය වැරදියි",
    "auth.createTitle": "ඔබගේ ගිණුම සාදන්න",
    "auth.createSubtitle": "AI සමඟ වඩා හොඳින් ඉගෙනීමට එක්වන්න.",
    "auth.fullName": "සම්පූර්ණ නම",
    "auth.fullNamePlaceholder": "ඔබගේ සම්පූර්ණ නම ඇතුළත් කරන්න", "auth.emailPlaceholder": "ඔබගේ විද්‍යුත් තැපැල් ලිපිනය ඇතුළත් කරන්න", "auth.passwordPlaceholder": "ශක්තිමත් මුරපදයක් සාදන්න", "auth.confirmPasswordPlaceholder": "ඔබගේ මුරපදය නැවත ඇතුළත් කරන්න", "auth.showPassword": "මුරපදය පෙන්වන්න", "auth.hidePassword": "මුරපදය සඟවන්න",
    "auth.confirmPassword": "මුරපදය තහවුරු කරන්න",
    "auth.rolePrompt": "මම",
    "auth.student": "ශිෂ්‍යයෙක්",
    "auth.teacher": "ගුරුවරයෙක්",
    "auth.createAccount": "ගිණුම සාදන්න",
    "auth.haveAccount": "දැනටමත් ගිණුමක් තිබේද?",
    "auth.accountCreated": "ගිණුම සාදන ලදී! Learnfy AI වෙත සාදරයෙන් පිළිගනිමු.",
    "auth.registrationFailed": "ලියාපදිංචිය අසාර්ථකයි",
    "academic.enterSubject": "විෂය නම ඇතුළත් කරන්න", "academic.subjectRequired": "කරුණාකර විෂයක් ඇතුළත් කරන්න හෝ තෝරන්න.",
    "auth.nameRequired": "සම්පූර්ණ නම ඇතුළත් කරන්න", "auth.strongPassword": "ලොකු අකුරු, කුඩා අකුරු, අංකයක් සහ විශේෂ ලකුණක් සමඟ අක්ෂර 8+ භාවිත කරන්න", "auth.passwordMismatch": "මුරපද නොගැලපේ",
    "sidebar.studentVerification": "ශිෂ්‍ය තහවුරු කිරීම", "sidebar.studentVerifications": "ශිෂ්‍ය තහවුරු කිරීම්",
    "studentVerification.title": "ශිෂ්‍ය තහවුරු කිරීම", "studentVerification.subtitle": "වත්මන් පාසල්, විද්‍යාල හෝ විශ්වවිද්‍යාල ලේඛනයක් මඟින් ඔබේ ශිෂ්‍ය තත්ත්වය තහවුරු කරන්න.",
    "studentVerification.loading": "තහවුරු කිරීමේ තත්ත්වය පූරණය වෙමින්...", "studentVerification.loadFailed": "ඔබේ තහවුරු කිරීමේ තත්ත්වය පූරණය කළ නොහැක.", "studentVerification.loadErrorTitle": "තහවුරු කිරීමේ තත්ත්වය නොමැත", "studentVerification.retry": "නැවත උත්සාහ කරන්න",
    "studentVerification.uploadTitle": "ශිෂ්‍ය සාක්ෂිය උඩුගත කරන්න", "studentVerification.uploadSubtitle": "ඔබේ ලේඛනය Learnfy AI පරිපාලකයෙකු විසින් පෞද්ගලිකව සමාලෝචනය කරනු ලැබේ.", "studentVerification.document": "ශිෂ්‍ය හැඳුනුම්පත හෝ ලියාපදිංචි ලේඛනය", "studentVerification.documentHelp": "PDF, JPG, JPEG හෝ PNG පමණි. උපරිම 5 MB.",
    "studentVerification.invalidFile": "5 MB දක්වා PDF, JPG හෝ PNG ගොනුවක් තෝරන්න.", "studentVerification.documentRequired": "තහවුරු කිරීමේ ලේඛනයක් තෝරන්න.", "studentVerification.submit": "තහවුරු කිරීමට යොමු කරන්න", "studentVerification.resubmit": "ලේඛනය නැවත යොමු කරන්න", "studentVerification.submitted": "තහවුරු කිරීමේ ලේඛනය යොමු කරන ලදී", "studentVerification.submitFailed": "ඔබේ ලේඛනය යොමු කළ නොහැක.",
    "studentVerification.statusTitle": "තහවුරු කිරීමේ තත්ත්වය", "studentVerification.currentStatus": "වත්මන් තත්ත්වය", "studentVerification.status.unverified": "තහවුරු කර නැත", "studentVerification.status.rejected": "අවධානය අවශ්‍යයි", "studentVerification.privacy": "ඔබේ සාක්ෂිය පෞද්ගලිකව ගබඩා කර ඇති අතර බලයලත් පරිපාලකයන්ට පමණක් ලබා ගත හැක.",
    "studentVerification.pendingTitle": "තහවුරු කිරීම සමාලෝචනය වෙමින් පවතී", "studentVerification.pendingMessage": "ඔබේ ලේඛනය සාර්ථකව යොමු කරන ලදී. පරිපාලකයෙකු එය සමාලෝචනය කරයි.", "studentVerification.verifiedTitle": "ශිෂ්‍යයා තහවුරු කර ඇත", "studentVerification.verifiedMessage": "ඔබේ ශිෂ්‍ය තත්ත්වය අනුමත කර ඇත. තහවුරු කළ ශිෂ්‍ය ලාංඡනය දැන් සක්‍රියයි.",
    "studentVerification.rejectedTitle": "තහවුරු කිරීමට අවධානය අවශ්‍යයි", "studentVerification.rejectedMessage": "යොමු කළ ලේඛනය අනුමත කළ නොහැකි විය.", "studentVerification.resubmitMessage": "ඉහත හේතුව සමාලෝචනය කර පැහැදිලි, වත්මන් ලේඛනයක් යොමු කරන්න.",
    "studentVerification.studentsOnlyTitle": "ශිෂ්‍ය ගිණුමක් අවශ්‍යයි", "studentVerification.studentsOnlyMessage": "ශිෂ්‍ය තහවුරු කිරීම ලබා ගත හැක්කේ ශිෂ්‍ය ගිණුම් සඳහා පමණි.", "studentVerification.backDashboard": "උපකරණ පුවරුවට ආපසු", "studentVerification.viewProfile": "පැතිකඩ බලන්න",
    "home.badge": "ඔබගේ බුද්ධිමත් අධ්‍යයන සහායකයා",
    "home.heroOne": "පැහැදිලිව ඉගෙන ගන්න.",
    "home.heroTwo": "Learnfy AI සමඟ වර්ධනය වන්න.",
    "home.description": "සටහන් සොයා, AI සමඟ ගැටලු විසඳා, ප්‍රශ්නාවලි පුහුණු වී, අධ්‍යයන සැලසුම් සාදන්න.",
    "home.startFree": "නොමිලේ ඉගෙනීම අරඹන්න",
    "home.exploreNotes": "සටහන් බලන්න",
    "home.easy": "භාවිතයට පහසුයි",
    "home.studentFriendly": "ශිෂ්‍ය හිතකාමී",
    "home.aiSupport": "AI සහාය",
    "home.allInOne": "සියල්ල එකම වේදිකාවක",
    "home.studySmarter": "වඩා බුද්ධිමත්ව ඉගෙන ගන්න",
    "home.toolsDescription": "ඉගෙනීම පැහැදිලි, සංවිධානාත්මක සහ ආකර්ෂණීය කරන ප්‍රයෝජනවත් මෙවලම්.",
    "home.featureDoubt": "AI ප්‍රශ්න විසඳුම",
    "home.featureDoubtDesc": "දුෂ්කර පාඩම් සඳහා සරල පියවරෙන් පියවර පැහැදිලි කිරීම් ලබාගන්න.",
    "home.featureNotes": "බුද්ධිමත් සටහන් බෙදාගැනීම",
    "home.featureNotesDesc": "සෑම විෂයකම සටහන් උඩුගත කර, සොයා, සුරකින්න සහ බාගන්න.",
    "home.featureGroups": "අධ්‍යයන කණ්ඩායම්",
    "home.featureGroupsDesc": "මිතුරන් සමඟ ඉගෙන, පාඩම් සාකච්ඡා කර, උනන්දුවෙන් සිටින්න.",
    "home.featureQuiz": "ප්‍රශ්නාවලි සාදකය",
    "home.featureQuizDesc": "ඕනෑම පාඩමක් පුහුණු ප්‍රශ්න බවට පත් කර විශ්වාසයෙන් සූදානම් වන්න.",
    "home.featureProgress": "පුද්ගලික ප්‍රගතිය",
    "home.featureProgressDesc": "අධ්‍යයන සැලැස්මක් සාදා, ප්‍රගතිය නිරීක්ෂණය කර, වැදගත් දේට අවධානය දෙන්න.",
    "home.featureSpace": "එක් ඉගෙනුම් අවකාශයක්",
    "home.featureSpaceDesc": "සටහන්, AI මෙවලම්, ප්‍රශ්නාවලි, කණ්ඩායම් සහ සැලසුම් එකම තැනක.",
    "home.journey": "ඔබගේ ඉගෙනුම් ගමන මෙතැනින් ආරම්භ වේ",
    "home.ready": "විශ්වාසයෙන් ඉගෙනීමට සූදානම්ද?",
    "home.ctaDescription": "නොමිලේ Learnfy AI ගිණුමක් සාදා සටහන්, ප්‍රශ්න, පුහුණුව සහ ප්‍රගතිය එකට ගන්න.",
    "home.createFree": "නොමිලේ ගිණුමක් සාදන්න",
    "sidebar.dashboard": "උපකරණ පුවරුව",
    "sidebar.notes": "සටහන්",
    "sidebar.resources": "සම්පත්",
    "sidebar.uploadNote": "සටහනක් උඩුගත කරන්න",
    "sidebar.aiDoubtSolver": "AI ප්‍රශ්න විසඳුම",
    "sidebar.aiSummarizer": "AI සාරාංශකය",
    "sidebar.quizGenerator": "ප්‍රශ්නාවලි සාදකය",
    "sidebar.studyPlanner": "අධ්‍යයන සැලැස්ම",
    "sidebar.flashcards": "ෆ්ලෑෂ් කාඩ්",
    "sidebar.studyGroups": "අධ්‍යයන කණ්ඩායම්",
    "sidebar.notesResources": "සටහන් සහ සම්පත්",
    "sidebar.teacherResources": "ගුරු සම්පත්",
    "sidebar.uploadMaterial": "පාඩම් ද්‍රව්‍ය උඩුගත කරන්න",
    "sidebar.aiAssistant": "AI සහායක",
    "sidebar.adminDashboard": "පරිපාලක උපකරණ පුවරුව", "sidebar.adminUsers": "පරිශීලකයින්", "sidebar.adminSubjects": "විෂයයන්", "sidebar.adminModeration": "අන්තර්ගත පාලනය", "sidebar.adminPayments": "ගෙවීම්", "sidebar.adminAuditLogs": "විගණන සටහන්", "admin.dashboardTitle": "පරිපාලක උපකරණ පුවරුව", "admin.usersTitle": "පරිශීලක කළමනාකරණය", "admin.moderationTitle": "අන්තර්ගත පාලනය", "admin.paymentsTitle": "ගෙවීම් සහ දායකත්ව", "admin.auditTitle": "පරිපාලක විගණන සටහන්",
    "sidebar.allNotes": "සියලු සටහන්",
    "sidebar.profile": "පැතිකඩ",
    "sidebar.settings": "සැකසුම්",
    "settings.title": "සැකසුම්",
    "settings.appearanceLanguage": "පෙනුම සහ භාෂාව",
    "settings.theme": "තේමාව",
    "settings.language": "පෙන්වන භාෂාව",
    "settings.accountDetails": "ගිණුම් විස්තර",
    "settings.fullName": "සම්පූර්ණ නම",
    "settings.email": "විද්‍යුත් තැපෑල",
    "settings.saveChanges": "වෙනස්කම් සුරකින්න",
    "settings.nameUpdated": "නම යාවත්කාලීන කරන ලදී",
    "settings.couldNotSave": "වෙනස්කම් සුරැකීමට නොහැකි විය",
    "settings.notifications": "දැනුම්දීම් මනාප",
    "settings.emailNotifications": "විද්‍යුත් තැපැල් දැනුම්දීම්",
    "settings.aiTips": "AI අධ්‍යයන උපදෙස් සහ මතක් කිරීම්",
    "settings.groupActivity": "අධ්‍යයන කණ්ඩායම් දැනුම්දීම්",
    "settings.privacy": "පෞද්ගලිකත්වය සහ ආරක්ෂාව",
    "settings.currentPassword": "වත්මන් මුරපදය",
    "settings.newPassword": "නව මුරපදය: ලොකු/කුඩා අකුරු, අංකය සහ විශේෂ සලකුණ",
    "settings.confirmPassword": "නව මුරපදය තහවුරු කරන්න",
    "settings.changePassword": "මුරපදය වෙනස් කරන්න",
    "settings.passwordMismatch": "නව මුරපද නොගැලපේ",
    "settings.passwordChanged": "මුරපදය වෙනස් කරන ලදී",
    "settings.couldNotChangePassword": "මුරපදය වෙනස් කළ නොහැකි විය",
    "settings.logoutDevice": "මෙම උපාංගයෙන් ඉවත් වන්න",
    "settings.deleteAccount": "ගිණුම මකන්න",
    "settings.deleteDescription": "මෙය ඔබගේ ගිණුම සහ අදාළ දත්ත ස්ථිරවම මකයි.",
    "settings.confirmCurrentPassword": "වත්මන් මුරපදයෙන් තහවුරු කරන්න",
    "settings.deleteMyAccount": "මගේ ගිණුම මකන්න",
    "settings.enterPassword": "පළමුව මුරපදය ඇතුළත් කරන්න",
    "settings.deleteConfirm": "Learnfy ගිණුම ස්ථිරවම මකන්නද?",
    "settings.accountDeleted": "ගිණුම මකා දමන ලදී",
    "settings.couldNotDelete": "ගිණුම මැකීමට නොහැකි විය",
    "quiz.title": "AI ප්‍රශ්නාවලි සාදකය",
    "quiz.subtitle": "ප්‍රශ්න සාදා, සියල්ලට පිළිතුරු දී, නිවැරදි පිළිතුරු සමඟ ලකුණු ලබාගන්න.",
    "quiz.subject": "විෂය",
    "quiz.questionCount": "ප්‍රශ්න ගණන",
    "quiz.topic": "මාතෘකාව",
    "quiz.topicPlaceholder": "උදා: නිව්ටන්ගේ චලිත නීති",
    "quiz.quizLanguage": "ප්‍රශ්න භාෂාව",
    "quiz.difficulty": "දුෂ්කරතා මට්ටම",
    "quiz.easy": "පහසු",
    "quiz.medium": "මධ්‍යම",
    "quiz.hard": "දුෂ්කර",
    "quiz.generate": "ප්‍රශ්නාවලිය සාදන්න",
    "quiz.generating": "ප්‍රශ්න සකස් කරමින්...",
    "quiz.enterTopic": "ප්‍රශ්න සෑදීමට මාතෘකාවක් ඇතුළත් කරන්න",
    "quiz.generateError": "ප්‍රශ්නාවලිය සෑදීමට නොහැකි විය",
    "quiz.answerAll": "යැවීමට පෙර සියලු ප්‍රශ්නවලට පිළිතුරු දෙන්න",
    "quiz.submit": "පිළිතුරු යවන්න",
    "quiz.submitting": "පිළිතුරු පරීක්ෂා කරමින්...",
    "quiz.submitError": "පිළිතුරු යැවීමට නොහැකි විය",
    "quiz.result": "ප්‍රශ්නාවලි ප්‍රතිඵලය",
    "quiz.score": "ලකුණු",
    "quiz.percentage": "ප්‍රතිශතය",
    "quiz.excellent": "විශිෂ්ටයි!",
    "quiz.good": "හොඳ උත්සාහයක්. පහත පිළිතුරු බලන්න.",
    "quiz.keepPractising": "තවදුරටත් පුහුණු වී නැවත උත්සාහ කරන්න.",
    "quiz.yourAnswer": "ඔබගේ පිළිතුර",
    "quiz.correctAnswer": "නිවැරදි පිළිතුර",
    "quiz.notAnswered": "පිළිතුරක් නැත",
    "quiz.correct": "නිවැරදි",
    "quiz.incorrect": "වැරදි",
    "quiz.newQuiz": "තවත් ප්‍රශ්නාවලියක්",
    "quiz.tryAgain": "නැවත උත්සාහ කරන්න",
    "groups.title": "අධ්‍යයන කණ්ඩායම්",
    "groups.create": "කණ්ඩායමක් සාදන්න",
    "groups.admin": "කණ්ඩායම් පරිපාලක",
    "groups.members": "සාමාජිකයින්",
    "groups.requests": "ඉල්ලීම්",
    "groups.leave": "ඉවත් වන්න",
    "groups.pending": "පොරොත්තුවෙන්",
    "groups.requestJoin": "එක්වීමට ඉල්ලන්න",
    "groups.delete": "මකන්න",
    "groups.discuss": "සාකච්ඡා",
    "groups.noGroups": "තවම අධ්‍යයන කණ්ඩායම් නැත — පළමු කණ්ඩායම සාදන්න!",
    "nav.pricing": "මිල ගණන්",
    "sidebar.payments": "Premium සහ ගෙවීම්",
    "payments.pricingTitle": "ඔබේ ඉගෙනුම් සැලැස්ම තෝරන්න",
    "payments.pricingSubtitle": "නොමිලේ ආරම්භ කරන්න හෝ Premium සමඟ සම්පූර්ණ Learnfy AI අත්දැකීම ලබා ගන්න.",
    "payments.bestValue": "හොඳම වටිනාකම",
    "payments.days": "දින",
    "payments.startFree": "නොමිලේ ආරම්භ කරන්න",
    "payments.choosePlan": "සැලැස්ම තෝරන්න",
    "payments.secureNotice": "ගෙවීම් PayHere මගින් ආරක්ෂිතව ක්‍රියාත්මක වේ. Learnfy AI ඔබේ සම්පූර්ණ කාඩ්පත් විස්තර ලබා නොගනී.",
    "payments.loadError": "ගෙවීම් සැලසුම් පූරණය කළ නොහැක",
    "payments.checkoutError": "ගෙවීම ආරම්භ කළ නොහැක",
    "payments.backToPlans": "සැලසුම් වෙත ආපසු",
    "payments.orderSummary": "ඇණවුම් සාරාංශය",
    "payments.daysAccess": "දින Premium ප්‍රවේශය",
    "payments.cardOnStripe": "PayHere ආරක්ෂිත ගෙවීම් පිටුවේ ඔබේ කාඩ්පත් විස්තර ඇතුළත් කරන්න.",
    "payments.billingDetails": "ගෙවීම් විස්තර",
    "payments.billingSubtitle": "PayHere ඔබේ ගෙවීම ආරක්ෂිතව ක්‍රියාත්මක කරයි.",
    "payments.phone": "දුරකථන අංකය",
    "payments.address": "ලිපිනය",
    "payments.city": "නගරය",
    "payments.country": "රට",
    "payments.continueStripe": "PayHere වෙත යන්න",
    "payments.noCardStorage": "කාඩ්පත් අංක හෝ CVV Learnfy AI හි ඇතුළත් හෝ ගබඩා නොවේ.",
    "payments.missingOrder": "ගෙවීම් ඇණවුම නොමැත",
    "payments.verifyError": "ගෙවීම් තත්ත්වය තහවුරු කළ නොහැක",
    "payments.successTitle": "ගෙවීම තහවුරු විය",
    "payments.pendingTitle": "ගෙවීම තහවුරු කරමින්",
    "payments.cancelledTitle": "ගෙවීම අවලංගු විය",
    "payments.failedTitle": "ගෙවීම අසාර්ථකයි",
    "payments.successMessage": "ඔබේ Premium ප්‍රවේශය දැන් සක්‍රියයි.",
    "payments.pendingMessage": "PayHere වෙතින් ආරක්ෂිත තහවුරු කිරීම බලාපොරොත්තුවෙන් සිටිමු.",
    "payments.cancelledMessage": "ගෙවීමක් තහවුරු වී නැත. පසුව නැවත උත්සාහ කළ හැක.",
    "payments.failedMessage": "PayHere මෙම ගෙවීම තහවුරු කළේ නැත.",
    "payments.orderId": "ඇණවුම් අංකය",
    "payments.amount": "මුදල",
    "payments.viewSubscription": "දායකත්වය බලන්න",
    "payments.tryAgain": "නැවත උත්සාහ කරන්න",
    "payments.premiumPayments": "Premium සහ ගෙවීම්",
    "payments.manageSubtitle": "ඔබේ Premium ප්‍රවේශය සහ ගෙවීම් ඉතිහාසය බලන්න.",
    "payments.currentPlan": "වත්මන් සැලැස්ම",
    "payments.activeUntil": "සක්‍රිය අවසානය",
    "payments.extendAccess": "ප්‍රවේශය දීර්ඝ කරන්න",
    "payments.upgrade": "Premium වෙත උසස් කරන්න",
    "payments.recentPayments": "මෑත ගෙවීම්",
    "payments.date": "දිනය",
    "payments.plan": "සැලැස්ම",
    "payments.status": "තත්ත්වය",
    "payments.noPayments": "තවම ගෙවීම් නොමැත.",
    "common.cancel": "අවලංගු කරන්න",
  },
};

const supportedLanguages = ["en", "ta", "si"];

export function PreferencesProvider({ children }) {
  const [theme, setThemeState] = useState(() => {
    const saved = localStorage.getItem("learnfy_theme");
    if (saved === "light" || saved === "dark") return saved;
    return window.matchMedia?.("(prefers-color-scheme: dark)").matches ? "dark" : "light";
  });
  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem("learnfy_language");
    return supportedLanguages.includes(saved) ? saved : "en";
  });

  useEffect(() => {
    document.documentElement.classList.toggle("dark", theme === "dark");
    document.documentElement.style.colorScheme = theme;
    localStorage.setItem("learnfy_theme", theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem("learnfy_language", language);
  }, [language]);

  const setTheme = useCallback((value) => {
    setThemeState(value === "dark" ? "dark" : "light");
  }, []);
  const toggleTheme = useCallback(() => {
    setThemeState((current) => (current === "dark" ? "light" : "dark"));
  }, []);
  const setLanguage = useCallback((value) => {
    if (supportedLanguages.includes(value)) setLanguageState(value);
  }, []);
  const t = useCallback(
    (key) => translations[language]?.[key] ?? translations.en[key] ?? key,
    [language]
  );

  const value = useMemo(
    () => ({ theme, setTheme, toggleTheme, language, setLanguage, t }),
    [theme, setTheme, toggleTheme, language, setLanguage, t]
  );

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export { PreferencesContext };
