import { useCallback, useEffect, useState } from "react";
import toast from "react-hot-toast";
import { FiEdit2, FiPlus, FiPower, FiSearch, FiTrash2 } from "react-icons/fi";
import ConfirmDialog from "../../components/ConfirmDialog";
import StreamSelect, { AL_STREAMS } from "../../components/subjects/StreamSelect";
import { createSubject, deleteSubject, getAcademicStreams, getAdminSubjects, getEducationLevels, getGrades, updateSubject } from "../../services/api";

const LEVELS = ["PRIMARY", "JUNIOR", "OL", "AL", "UNIVERSITY", "SELF"];
const blankFor = (level) => ({ level, stream: level === "AL" ? "Engineering Technology" : "General", streams: [level === "AL" ? "Engineering Technology" : "General"], subject_code: "", name_en: "", name_ta: "", name_si: "", description: "", is_active: true, sort_order: 0 });

export default function SubjectManagement(){const[items,setItems]=useState([]),[level,setLevel]=useState("AL"),[stream,setStream]=useState(""),[search,setSearch]=useState(""),[form,setForm]=useState(null),[saving,setSaving]=useState(false),[removeItem,setRemoveItem]=useState(null),[catalogue,setCatalogue]=useState({levels:0,grades:0,streams:0,mediums:3}),[error,setError]=useState("");
const load=useCallback(async()=>{setError("");try{setItems((await getAdminSubjects({level,stream:level==="AL"?stream||undefined:undefined,search:search||undefined})).data)}catch(e){setError(e.response?.data?.detail||"Could not load subjects")}},[level,stream,search]);useEffect(()=>{load()},[load]);useEffect(()=>{Promise.all([getEducationLevels(),getGrades({}),getAcademicStreams()]).then(([levels,grades,streams])=>setCatalogue({levels:levels.data.length,grades:grades.data.length,streams:streams.data.length,mediums:3})).catch(()=>{})},[]);
const save=async e=>{e.preventDefault();setSaving(true);try{form.id?await updateSubject(form.id,form):await createSubject(form);toast.success("Subject saved");setForm(null);load()}catch(err){toast.error(err.response?.data?.detail||"Could not save subject")}finally{setSaving(false)}};const remove=async()=>{setSaving(true);try{await deleteSubject(removeItem.id);toast.success("Subject removed or safely deactivated");setRemoveItem(null);load()}catch(err){toast.error(err.response?.data?.detail||"Could not delete subject")}finally{setSaving(false)}};const toggle=async item=>{try{await updateSubject(item.id,{...item,is_active:!item.is_active});toast.success(item.is_active?"Subject deactivated":"Subject activated");load()}catch(e){toast.error(e.response?.data?.detail||"Could not update subject")}};
return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="page-title">Subject Management</h1><p className="mt-1 text-sm text-slate-500">Shared catalogue for registration, notes, resources, and study groups.</p></div><button className="btn-primary" onClick={()=>setForm(blankFor(level))}><FiPlus/>Add subject</button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries(catalogue).map(([key,value])=><div key={key} className="rounded-lg border border-slate-200 bg-white p-3 dark:border-slate-700 dark:bg-slate-900"><p className="text-xl font-bold">{value}</p><p className="text-xs capitalize text-slate-500">{key}</p></div>)}</div><div className="grid gap-3 sm:grid-cols-3"><select className="input-field" value={level} onChange={e=>{setLevel(e.target.value);setStream("")}}>{LEVELS.map(value=><option key={value}>{value}</option>)}</select>{level==="AL"?<StreamSelect value={stream} includeAll onChange={setStream}/>:<div className="input-field text-sm text-slate-500">All categories</div>}<label className="relative"><FiSearch className="absolute left-3 top-3.5 text-slate-400"/><input className="input-field pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search code or name"/></label></div>{error&&<div role="alert" className="rounded-lg bg-red-50 p-4 text-red-700 dark:bg-red-950/40 dark:text-red-200">{error}</div>}
{form&&<form onSubmit={save} className="grid gap-3 rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900 sm:grid-cols-2"><h2 className="font-bold sm:col-span-2">{form.id?"Edit subject":"Add subject"}</h2><label className="text-sm font-medium">Education level<select className="input-field mt-1" value={form.level} onChange={e=>setForm({...form,...blankFor(e.target.value),id:form.id})}>{LEVELS.map(value=><option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium">Subject code<input className="input-field mt-1" required pattern="[A-Z0-9][A-Z0-9-]{0,9}" value={form.subject_code} onChange={e=>setForm({...form,subject_code:e.target.value.toUpperCase()})}/></label>{form.level==="AL"?<label className="text-sm font-medium">Primary stream<StreamSelect value={form.stream} onChange={value=>setForm({...form,stream:value,streams:[value]})}/></label>:<label className="text-sm font-medium">Category<input className="input-field mt-1" required value={form.stream} onChange={e=>setForm({...form,stream:e.target.value,streams:[e.target.value]})}/></label>}<label className="text-sm font-medium">Sort order<input type="number" min="0" className="input-field mt-1" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label><label className="text-sm font-medium">English name<input className="input-field mt-1" required value={form.name_en} onChange={e=>setForm({...form,name_en:e.target.value})}/></label><label className="text-sm font-medium">Tamil name<input className="input-field mt-1" required value={form.name_ta} onChange={e=>setForm({...form,name_ta:e.target.value})}/></label><label className="text-sm font-medium">Sinhala name<input className="input-field mt-1" required value={form.name_si} onChange={e=>setForm({...form,name_si:e.target.value})}/></label><label className="text-sm font-medium sm:col-span-2">Description<textarea className="input-field mt-1" value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})}/></label>{form.level==="AL"&&<fieldset className="sm:col-span-2"><legend className="mb-2 text-sm font-semibold">Available streams</legend><div className="flex flex-wrap gap-3">{AL_STREAMS.map(value=><label key={value} className="text-sm"><input type="checkbox" className="mr-1" checked={form.streams.includes(value)} onChange={e=>setForm({...form,streams:e.target.checked?[...form.streams,value]:form.streams.filter(x=>x!==value)})}/>{value}</label>)}</div></fieldset>}<div className="flex gap-2 sm:col-span-2"><button disabled={saving} className="btn-primary">{saving?"Saving...":"Save"}</button><button type="button" className="btn-secondary" onClick={()=>setForm(null)}>Cancel</button></div></form>}
<div className="overflow-x-auto rounded-lg border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-slate-500 dark:bg-slate-800"><tr><th className="p-3">Code</th><th>Name</th><th>Level / Streams</th><th>Status</th><th className="pr-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{items.map(item=><tr key={item.id}><td className="p-3 font-bold">{item.subject_code}</td><td><p className="font-semibold">{item.name_en}</p><p className="text-xs text-slate-400">{item.name_ta} / {item.name_si}</p></td><td className="max-w-xs text-xs text-slate-500">{item.level} / {item.streams.join(", ")}</td><td>{item.is_active?"Active":"Inactive"}</td><td><div className="flex justify-end gap-1 pr-3"><button aria-label="Edit" className="rounded p-2 hover:bg-slate-100" onClick={()=>setForm({...item})}><FiEdit2/></button><button aria-label="Toggle active" className="rounded p-2 hover:bg-amber-50" onClick={()=>toggle(item)}><FiPower/></button><button aria-label="Delete" className="rounded p-2 text-red-500 hover:bg-red-50" onClick={()=>setRemoveItem(item)}><FiTrash2/></button></div></td></tr>)}</tbody></table>{!items.length&&<p className="p-10 text-center text-slate-500">No subjects found for this level.</p>}</div><ConfirmDialog open={!!removeItem} title="Delete subject?" message="Subjects already used by learning content will be safely deactivated instead of removed." confirmLabel="Delete or deactivate" danger busy={saving} onCancel={()=>setRemoveItem(null)} onConfirm={remove}/></div>}
