import { useEffect, useId, useMemo, useRef, useState } from "react";
import { getSubjects } from "../../services/api";
import { usePreferences } from "../../hooks/usePreferences";

export const subjectLabel = (subject, language) => `${subject.subject_code} – ${subject[`name_${language}`] || subject.name_en}`;

export default function SubjectSelect({ stream, gradeId, medium, level, value, selectedId, onChange, includeAll=false, allowCustom=false, disabled=false, className="input-field", required=false }) {
  const { language,t }=usePreferences();
  const [subjects,setSubjects]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[activeIndex,setActiveIndex]=useState(0),[validationVisible,setValidationVisible]=useState(false);
  const rootRef=useRef(null),listId=useId();
  useEffect(()=>{let active=true;if(!gradeId&&!level){setSubjects([]);setError("");return()=>{active=false}}setLoading(true);setError("");getSubjects({level:level||undefined,grade_id:gradeId||undefined,medium:medium||undefined,stream:stream||undefined}).then(({data})=>{if(active)setSubjects(Array.isArray(data)?data:data?.items||[])}).catch(requestError=>{if(active){setSubjects([]);setError(requestError.response?.data?.detail||"Could not load subjects")}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[stream,gradeId,medium,level]);
  const selected=useMemo(()=>subjects.find(item=>String(item.id)===String(selectedId)||item.name_en===value),[subjects,selectedId,value]);
  const display=selected?subjectLabel(selected,language):value||"";
  useEffect(()=>setQuery(display),[display]);
  const filtered=useMemo(()=>{const term=query.trim().toLocaleLowerCase();return subjects.filter(subject=>!term||subjectLabel(subject,language).toLocaleLowerCase().includes(term)||subject.name_en.toLocaleLowerCase().includes(term))},[subjects,query,language]);
  const choose=item=>{setValidationVisible(false);if(!item){onChange("");setQuery("")}else{onChange(item.name_en,item);setQuery(subjectLabel(item,language))}setOpen(false)};
  const keepCustom=()=>{const custom=query.trim();onChange(custom,null);setQuery(custom);setValidationVisible(required&&custom.length<2)};
  useEffect(()=>{const outside=event=>{if(!rootRef.current?.contains(event.target)){setOpen(false);if(allowCustom)keepCustom();else setQuery(display)}};document.addEventListener("pointerdown",outside);return()=>document.removeEventListener("pointerdown",outside)});
  const keyDown=event=>{if(event.key==="Escape"){setOpen(false);setQuery(display);return}if(event.key==="ArrowDown"||event.key==="ArrowUp"){event.preventDefault();setOpen(true);setActiveIndex(index=>event.key==="ArrowDown"?Math.min(index+1,filtered.length-1):Math.max(index-1,0))}if(event.key==="Enter"){if(open&&filtered[activeIndex]){event.preventDefault();choose(filtered[activeIndex])}else if(allowCustom){event.preventDefault();keepCustom()}}};
  const invalid=required&&(allowCustom?query.trim().length<2:!selectedId);
  return <div ref={rootRef} className="relative z-20"><input role="combobox" aria-autocomplete="list" aria-controls={listId} aria-expanded={open} aria-invalid={validationVisible&&invalid} className={className} value={query} disabled={disabled||loading} required={required} pattern={required&&!allowCustom&&!selectedId?"(?!)":undefined} minLength={required&&allowCustom?2:undefined} placeholder={loading?"Loading subjects…":allowCustom?t("academic.enterSubject"):includeAll?"All subjects":"Search or select a subject"} onFocus={()=>setOpen(true)} onClick={()=>setOpen(true)} onKeyDown={keyDown} onBlur={()=>{if(allowCustom)keepCustom()}} onInvalid={event=>{event.preventDefault();setValidationVisible(true)}} onChange={event=>{const next=event.target.value;setQuery(next);setOpen(true);setActiveIndex(0);setValidationVisible(false);if(allowCustom)onChange(next,null);else if(next!==display)onChange("",null);if(!next&&includeAll)onChange("")}}/>
    {open&&!loading&&!disabled&&<div id={listId} role="listbox" className="absolute left-0 right-0 top-full z-30 mt-1 max-h-64 overflow-y-auto rounded-xl border border-slate-200 bg-white p-1 shadow-xl dark:border-slate-600 dark:bg-slate-900">{includeAll&&<button type="button" role="option" onClick={()=>choose(null)} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-100 dark:hover:bg-slate-800">All subjects</button>}{filtered.length?filtered.map((subject,index)=><button type="button" role="option" aria-selected={String(subject.id)===String(selectedId)} key={subject.id} onMouseEnter={()=>setActiveIndex(index)} onClick={()=>choose(subject)} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${index===activeIndex?"bg-primary-50 text-primary-700 dark:bg-slate-800 dark:text-primary-300":"hover:bg-slate-50 dark:hover:bg-slate-800"}`}>{subjectLabel(subject,language)}</button>):allowCustom?null:<p className="px-3 py-3 text-sm text-slate-500">No options available</p>}</div>}
    {validationVisible&&invalid&&<p className="mt-1 text-xs text-red-500" role="alert">{t("academic.subjectRequired")}</p>}{error&&<p className="mt-1 text-xs text-red-500" role="alert">{error}</p>}{!allowCustom&&!loading&&!error&&(gradeId||level)&&!subjects.length&&<p className="mt-1 text-xs text-slate-500">No options available</p>}</div>;
}
