import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { FiBookOpen, FiCheck, FiUser, FiUsers, FiX } from "react-icons/fi";
import { useAuth } from "../../hooks/useAuth";
import { usePreferences } from "../../hooks/usePreferences";
import EducationLevelSelect from "../../components/subjects/EducationLevelSelect";
import GradeSelect from "../../components/subjects/GradeSelect";
import MediumSelect from "../../components/subjects/MediumSelect";
import StreamSelect from "../../components/subjects/StreamSelect";
import SubjectSelect from "../../components/subjects/SubjectSelect";

const copy = {
  en: { title:"Complete your Learnfy profile", subtitle:"Personalize your learning experience once, then reuse it everywhere.", role:"How will you use Learnfy AI?", student:"Student", teacher:"Teacher", details:"Academic information", level:"Education level", grade:"Grade", medium:"Learning medium", stream:"Stream", subjects:"Subjects", teachingGrades:"Teaching grades", specializations:"Subject specializations", school:"School or institution (optional)", district:"District (optional)", previous:"Previous", continue:"Continue", complete:"Complete Setup", pending:"Teacher accounts remain unverified until an administrator approves verification." },
  ta: { title:"உங்கள் Learnfy சுயவிவரத்தை நிறைவு செய்யுங்கள்", subtitle:"உங்கள் கற்றல் அனுபவத்தை ஒருமுறை அமைத்து எங்கும் பயன்படுத்துங்கள்.", role:"Learnfy AI-ஐ எவ்வாறு பயன்படுத்துவீர்கள்?", student:"மாணவர்", teacher:"ஆசிரியர்", details:"கல்வித் தகவல்", level:"கல்வி நிலை", grade:"தரம்", medium:"கற்றல் மொழி", stream:"பிரிவு", subjects:"பாடங்கள்", teachingGrades:"கற்பிக்கும் தரங்கள்", specializations:"பாட நிபுணத்துவங்கள்", school:"பள்ளி அல்லது நிறுவனம் (விருப்பம்)", district:"மாவட்டம் (விருப்பம்)", previous:"முந்தையது", continue:"தொடரவும்", complete:"அமைப்பை முடிக்கவும்", pending:"நிர்வாகி சரிபார்ப்பை அங்கீகரிக்கும் வரை ஆசிரியர் கணக்கு சரிபார்க்கப்படாது." },
  si: { title:"ඔබගේ Learnfy පැතිකඩ සම්පූර්ණ කරන්න", subtitle:"ඔබගේ ඉගෙනුම් අත්දැකීම එක් වරක් සකසා සෑම තැනම භාවිත කරන්න.", role:"ඔබ Learnfy AI භාවිත කරන්නේ කෙසේද?", student:"ශිෂ්‍ය", teacher:"ගුරුවරයා", details:"අධ්‍යාපනික තොරතුරු", level:"අධ්‍යාපන මට්ටම", grade:"ශ්‍රේණිය", medium:"ඉගෙනුම් මාධ්‍යය", stream:"විෂය ධාරාව", subjects:"විෂයයන්", teachingGrades:"උගන්වන ශ්‍රේණි", specializations:"විෂය විශේෂීකරණ", school:"පාසල හෝ ආයතනය (විකල්ප)", district:"දිස්ත්‍රික්කය (විකල්ප)", previous:"පෙර", continue:"ඉදිරියට", complete:"සැකසුම සම්පූර්ණ කරන්න", pending:"පරිපාලක අනුමැතිය ලැබෙන තෙක් ගුරු ගිණුම සත්‍යාපිත නොවේ." },
};

export default function Onboarding() {
  const { finishOnboarding } = useAuth(); const { language } = usePreferences(); const navigate = useNavigate(); const text=copy[language]||copy.en;
  const [step,setStep]=useState(1),[role,setRole]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const [form,setForm]=useState({education_level_id:"",levelCode:"",grade_id:"",gradeLabel:"",medium:"",stream:"",stream_id:null,subject:"",subject_id:null,subject_ids:[],subjects:[],teacher_grade_ids:[],teacherGrades:[],school_name:"",district:""});
  const schoolLevel=["PRIMARY","JUNIOR","OL","AL"].includes(form.levelCode); const teacher=role==="teacher";
  const update=patch=>setForm(current=>({...current,...patch}));
  const addSubject=()=>{if(!form.subject_id||form.subject_ids.includes(Number(form.subject_id)))return;update({subject_ids:[...form.subject_ids,Number(form.subject_id)],subjects:[...form.subjects,{id:Number(form.subject_id),name:form.subject}],subject:"",subject_id:null})};
  const addGrade=()=>{if(!form.grade_id||form.teacher_grade_ids.includes(Number(form.grade_id)))return;update({teacher_grade_ids:[...form.teacher_grade_ids,Number(form.grade_id)],teacherGrades:[...form.teacherGrades,{id:Number(form.grade_id),name:form.gradeLabel}]})};
  const valid=useMemo(()=>role&&form.education_level_id&&form.medium&&(!schoolLevel||form.grade_id)&&(form.levelCode!=="AL"||form.stream_id)&&form.subject_ids.length&&(!teacher||form.teacher_grade_ids.length),[role,form,schoolLevel,teacher]);
  const submit=async event=>{event.preventDefault();setError("");if(!valid){setError("Complete all required academic fields and add at least one subject.");return}setSaving(true);try{const user=await finishOnboarding({role,education_level_id:Number(form.education_level_id),grade_id:form.grade_id?Number(form.grade_id):null,stream_id:form.stream_id||null,medium:form.medium,subject_ids:form.subject_ids,teacher_grade_ids:teacher?form.teacher_grade_ids:[],teacher_subject_ids:teacher?form.subject_ids:[],school_name:form.school_name||null,district:form.district||null});toast.success("Profile setup complete");navigate(user.role==="teacher"?"/teacher-verification":"/dashboard",{replace:true})}catch(requestError){setError(requestError.response?.data?.detail||"Could not complete setup. Please try again.")}finally{setSaving(false)}};
  const chips=(items,key)=>items.map(item=><span key={item.id} className="inline-flex items-center gap-2 rounded-full bg-primary-50 px-3 py-1 text-sm font-semibold text-primary-700 dark:bg-primary-950/50 dark:text-primary-200">{item.name}<button type="button" aria-label={`Remove ${item.name}`} onClick={()=>update({[key]:form[key].filter(id=>id!==item.id),[key==="subject_ids"?"subjects":"teacherGrades"]:items.filter(value=>value.id!==item.id)})}><FiX /></button></span>);
  return <main className="mx-auto w-full max-w-4xl py-4 sm:py-8"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl dark:border-slate-700 dark:bg-slate-900">
    <header className="border-b border-slate-200 bg-gradient-to-r from-primary-600 to-indigo-600 p-6 text-white dark:border-slate-700 sm:p-8"><p className="text-sm font-bold uppercase tracking-widest">Learnfy AI</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">{text.title}</h1><p className="mt-2 max-w-2xl text-primary-100">{text.subtitle}</p><div className="mt-6 grid grid-cols-2 gap-3" aria-label="Onboarding progress">{[1,2].map(value=><div key={value} className={`h-2 rounded-full ${value<=step?"bg-white":"bg-white/30"}`} />)}</div></header>
    <form onSubmit={submit} className="p-6 sm:p-8">{step===1?<fieldset><legend className="text-xl font-bold text-slate-900 dark:text-white">{text.role}</legend><div className="mt-6 grid gap-4 sm:grid-cols-2">{[["student",FiUser,text.student],["teacher",FiUsers,text.teacher]].map(([value,Icon,label])=><button key={value} type="button" aria-pressed={role===value} onClick={()=>setRole(value)} className={`rounded-2xl border-2 p-6 text-left transition focus:outline-none focus:ring-2 focus:ring-primary-500 ${role===value?"border-primary-500 bg-primary-50 dark:bg-primary-950/40":"border-slate-200 hover:border-primary-300 dark:border-slate-700"}`}><Icon size={28} className="text-primary-600"/><span className="mt-4 block text-lg font-bold dark:text-white">{label}</span><span className="mt-1 block text-sm text-slate-500">{value==="student"?"Learn with personalized content and AI tools.":"Teach learners and share verified educational content."}</span></button>)}</div></fieldset>:<fieldset><legend className="flex items-center gap-2 text-xl font-bold text-slate-900 dark:text-white"><FiBookOpen className="text-primary-600"/>{text.details}</legend><div className="mt-6 grid gap-5 sm:grid-cols-2">
      <label className="space-y-2 text-sm font-semibold dark:text-slate-200"><span>{text.level}</span><EducationLevelSelect value={form.education_level_id} onChange={(id,item)=>update({education_level_id:id,levelCode:item?.code||"",grade_id:"",teacher_grade_ids:[],teacherGrades:[],stream:"",stream_id:null,subject_ids:[],subjects:[]})} required /></label>
      {schoolLevel&&<label className="space-y-2 text-sm font-semibold dark:text-slate-200"><span>{teacher?text.teachingGrades:text.grade}</span><div className="flex gap-2"><GradeSelect levelId={form.education_level_id} value={form.grade_id} onChange={(id,item)=>update({grade_id:id,gradeLabel:item?.name_en||"",subject_ids:[],subjects:[]})} required /><button type="button" onClick={addGrade} className="btn-secondary" hidden={!teacher}>Add</button></div>{teacher&&<div className="flex flex-wrap gap-2">{chips(form.teacherGrades,"teacher_grade_ids")}</div>}</label>}
      <label className="space-y-2 text-sm font-semibold dark:text-slate-200"><span>{text.medium}</span><MediumSelect value={form.medium} onChange={medium=>update({medium,subject_ids:[],subjects:[]})} required /></label>
      {form.levelCode==="AL"&&<label className="space-y-2 text-sm font-semibold dark:text-slate-200"><span>{text.stream}</span><StreamSelect value={form.stream} onChange={(stream,item)=>update({stream,stream_id:item?.id||null,subject_ids:[],subjects:[]})} required /></label>}
      <div className="space-y-2 sm:col-span-2"><label className="text-sm font-semibold dark:text-slate-200">{teacher?text.specializations:text.subjects}</label><div className="flex gap-2"><div className="flex-1"><SubjectSelect gradeId={form.grade_id} medium={form.medium} level={!form.grade_id?form.levelCode:""} stream={form.levelCode==="AL"?form.stream:""} value={form.subject} selectedId={form.subject_id} onChange={(subject,item)=>update({subject,subject_id:item?.id||null})} disabled={!form.education_level_id||(schoolLevel&&!form.grade_id)||(form.levelCode==="AL"&&!form.stream)} /></div><button type="button" className="btn-secondary" onClick={addSubject}>Add</button></div><div className="flex flex-wrap gap-2">{chips(form.subjects,"subject_ids")}</div></div>
      <label className="space-y-2 text-sm font-semibold dark:text-slate-200"><span>{text.school}</span><input className="input-field" maxLength="255" value={form.school_name} onChange={event=>update({school_name:event.target.value})}/></label><label className="space-y-2 text-sm font-semibold dark:text-slate-200"><span>{text.district}</span><input className="input-field" maxLength="100" value={form.district} onChange={event=>update({district:event.target.value})}/></label>
    </div>{teacher&&<p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200">{text.pending}</p>}</fieldset>}
    {error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/40 dark:text-red-200">{error}</p>}<div className="mt-8 flex justify-between border-t border-slate-200 pt-6 dark:border-slate-700">{step===2?<button type="button" className="btn-secondary" disabled={saving} onClick={()=>setStep(1)}>{text.previous}</button>:<span/>}{step===1?<button type="button" className="btn-primary" disabled={!role} onClick={()=>setStep(2)}>{text.continue}</button>:<button type="submit" className="btn-primary" disabled={saving||!valid}>{saving?"Saving…":<><FiCheck/>{text.complete}</>}</button>}</div>
    </form></section></main>;
}
