import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { FiMail } from "react-icons/fi";
import { useAuth } from "../../hooks/useAuth";
import { requestEmailVerification } from "../../services/api";

export default function VerifyEmail(){const{confirmEmail,user}=useAuth(),navigate=useNavigate();const[code,setCode]=useState(""),[loading,setLoading]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState("");
  const send=useCallback(async()=>{setError("");try{await requestEmailVerification();setSent(true);toast.success("Verification code sent")}catch(requestError){setError(requestError.response?.data?.detail||"Could not send verification code")}},[]);
  useEffect(()=>{if(!sent)send()},[send,sent]);const submit=async event=>{event.preventDefault();if(!/^\d{6}$/.test(code)){setError("Enter the six-digit verification code");return}setLoading(true);setError("");try{await confirmEmail(code);navigate("/onboarding",{replace:true})}catch(requestError){setError(requestError.response?.data?.detail||"Invalid verification code")}finally{setLoading(false)}};
  return <main className="mx-auto flex min-h-[65vh] max-w-xl items-center"><section className="w-full rounded-2xl border border-slate-200 bg-white p-6 text-center shadow-xl dark:border-slate-700 dark:bg-slate-900 sm:p-10"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-primary-50 text-primary-600 dark:bg-primary-950/50"><FiMail size={26}/></span><h1 className="mt-5 text-2xl font-black dark:text-white">Verify your email</h1><p className="mt-2 text-sm leading-6 text-slate-500">We sent a six-digit code to <strong>{user?.email}</strong>. Verify it before setting up your profile.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-left text-sm font-semibold dark:text-slate-200">Verification code<input autoFocus inputMode="numeric" autoComplete="one-time-code" maxLength="6" className="input-field mt-2 text-center text-xl tracking-[0.4em]" value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,""))}/></label>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={loading||code.length!==6} className="btn-primary w-full">{loading?"Verifying…":"Verify email"}</button></form><button type="button" onClick={send} className="mt-5 text-sm font-semibold text-primary-600 hover:underline">Send a new code</button></section></main>}
