import { useCallback, useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { FiHeart, FiLayers, FiPlus, FiSearch } from "react-icons/fi";
import toast from "react-hot-toast";

import FlashcardDashboardStats from "../../components/flashcards/FlashcardDashboardStats";
import FlashcardGeneratorForm from "../../components/flashcards/FlashcardGeneratorForm";
import FlashcardReminderSettings from "../../components/flashcards/FlashcardReminderSettings";
import FlashcardViewer from "../../components/flashcards/FlashcardViewer";
import Loader from "../../components/Loader";
import { getFlashcardSets, getFlashcardStats, saveFlashcardSet, toggleFlashcardSetFavourite } from "../../services/api";

export default function Flashcards() {
  const [searchParams] = useSearchParams(); const initialNoteId = searchParams.get("noteId");
  const [view, setView] = useState(initialNoteId ? "create" : "saved"); const [generated, setGenerated] = useState(null); const [sets, setSets] = useState([]); const [stats, setStats] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [filters, setFilters] = useState({ search: "", subject: "", favourites: false, sort: "newest" });
  const load = useCallback(async () => { setLoading(true); try { const [setResponse, statResponse] = await Promise.all([getFlashcardSets({ ...filters, search: filters.search || undefined, subject: filters.subject || undefined }), getFlashcardStats()]); setSets(setResponse.data); setStats(statResponse.data); } catch { toast.error("Could not load saved flashcards"); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { const timer = window.setTimeout(load, 250); return () => window.clearTimeout(timer); }, [load]);

  const save = async () => { if (!generated || saving) return; setSaving(true); try { const response = await saveFlashcardSet({ title: generated.title, subject: generated.subject, source_type: generated.source_type, source_name: generated.source_name, language: generated.language, difficulty: generated.difficulty, cards: generated.cards.map((card) => ({ question: card.question, answer: card.answer, image_url: null })) }); toast.success("Flashcard set saved"); setGenerated(null); setView("saved"); await load(); return response.data; } catch (error) { toast.error(error.response?.data?.detail || "Saving failed. Your generated cards are still here."); } finally { setSaving(false); } };
  const favourite = async (item) => { try { const response = await toggleFlashcardSetFavourite(item.id); setSets((current) => current.map((entry) => entry.id === item.id ? response.data : entry)); } catch { toast.error("Could not update favourite"); } };

  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="page-title flex items-center gap-2"><FiLayers /> AI Flashcards</h1><p className="mt-1 text-sm text-slate-500">Create, study, save, revise, and share private learning sets.</p></div><button onClick={() => setView("create")} className="btn-primary"><FiPlus /> Create New Flashcards</button></div>
    <FlashcardDashboardStats stats={stats} />
    <div className="flex gap-2 border-b border-slate-200 dark:border-slate-700">{[["saved", "My Sets"], ["create", "Generate"], ["favourites", "Favourites"]].map(([id, label]) => <button key={id} onClick={() => { setView(id); setFilters((old) => ({ ...old, favourites: id === "favourites" })); }} className={`border-b-2 px-4 py-3 text-sm font-bold ${view === id ? "border-primary-600 text-primary-600" : "border-transparent text-slate-500"}`}>{label}</button>)}</div>
    {view === "create" ? <section className="rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900 md:p-7"><FlashcardGeneratorForm initialNoteId={initialNoteId} onGenerated={setGenerated} />{generated && <div className="mt-8 space-y-5 border-t border-slate-200 pt-7 dark:border-slate-700"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-xl font-black text-slate-900 dark:text-white">{generated.title}</h2><p className="text-sm text-slate-500">{generated.subject} · {generated.difficulty} · {generated.cards.length} cards</p></div><button disabled={saving} onClick={save} className="btn-primary">{saving ? "Saving..." : "Save Set"}</button></div><FlashcardViewer cards={generated.cards} language={generated.language} readOnly /></div>}</section> : <>
      <div className="grid gap-3 md:grid-cols-[1fr_180px_160px]"><label className="relative"><FiSearch className="absolute left-3 top-3.5 text-slate-400" /><input className="input-field pl-10" placeholder="Search title or subject" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /></label><select className="input-field" value={filters.subject} onChange={(e) => setFilters({ ...filters, subject: e.target.value })}><option value="">All subjects</option>{[...new Set(sets.map((item) => item.subject))].map((item) => <option key={item}>{item}</option>)}</select><select className="input-field" value={filters.sort} onChange={(e) => setFilters({ ...filters, sort: e.target.value })}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="title">Title</option><option value="highest_score">Highest score</option></select></div>
      {loading ? <Loader label="Loading flashcards..." /> : sets.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{sets.map((item) => <article key={item.id} className="rounded-lg border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><div className="flex justify-between gap-3"><span className="rounded bg-primary-50 px-2 py-1 text-xs font-bold text-primary-700">{item.subject}</span><button aria-label="Favourite set" onClick={() => favourite(item)} className={item.is_favourite ? "text-red-500" : "text-slate-400"}><FiHeart className={item.is_favourite ? "fill-current" : ""} /></button></div><h2 className="mt-4 line-clamp-2 text-lg font-bold text-slate-900 dark:text-white">{item.title}</h2><p className="mt-2 text-sm text-slate-500">{item.cards.length} cards · {item.difficulty} · {item.language.toUpperCase()}</p><div className="mt-5 flex items-center justify-between"><span className="text-xs font-semibold text-emerald-600">Best: {item.best_score == null ? "—" : `${Math.round(item.best_score)}%`}</span><Link to={`/flashcards/${item.id}`} className="btn-secondary">Open</Link></div></article>)}</div> : <div className="rounded-lg border border-dashed border-slate-300 py-14 text-center dark:border-slate-700"><FiLayers className="mx-auto text-slate-300" size={42} /><h2 className="mt-3 font-bold dark:text-white">No flashcard sets found</h2><p className="mt-1 text-sm text-slate-500">Generate and save your first set to begin studying.</p></div>}
    </>}
    <FlashcardReminderSettings />
  </div>;
}
