-- Repeat-safe normalized Sri Lankan Grade 1-13 academic master data.
CREATE TABLE IF NOT EXISTS education_levels(id INT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(30) NOT NULL UNIQUE,name_en VARCHAR(100) NOT NULL,name_ta VARCHAR(100) NOT NULL,name_si VARCHAR(100) NOT NULL,sort_order INT DEFAULT 0,is_active BOOLEAN DEFAULT TRUE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS grades(id INT AUTO_INCREMENT PRIMARY KEY,level_id INT NOT NULL,code VARCHAR(30) NOT NULL UNIQUE,name_en VARCHAR(100) NOT NULL,name_ta VARCHAR(100) NOT NULL,name_si VARCHAR(100) NOT NULL,grade_number INT,sort_order INT DEFAULT 0,is_active BOOLEAN DEFAULT TRUE,FOREIGN KEY(level_id) REFERENCES education_levels(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS streams(id INT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50) NOT NULL UNIQUE,name_en VARCHAR(100) NOT NULL,name_ta VARCHAR(100) NOT NULL,name_si VARCHAR(100) NOT NULL,is_active BOOLEAN DEFAULT TRUE,sort_order INT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS grade_subjects(id INT AUTO_INCREMENT PRIMARY KEY,grade_id INT NOT NULL,subject_id INT NOT NULL,medium VARCHAR(10) NOT NULL DEFAULT 'all',sort_order INT DEFAULT 0,is_active BOOLEAN DEFAULT TRUE,UNIQUE KEY uq_grade_subject_medium(grade_id,subject_id,medium),FOREIGN KEY(grade_id) REFERENCES grades(id) ON DELETE CASCADE,FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS user_academic_profiles(user_id INT PRIMARY KEY,education_level_id INT,grade_id INT,stream_id INT,medium VARCHAR(10),school_name VARCHAR(255),district VARCHAR(100),guardian_consent BOOLEAN DEFAULT FALSE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(education_level_id) REFERENCES education_levels(id),FOREIGN KEY(grade_id) REFERENCES grades(id),FOREIGN KEY(stream_id) REFERENCES streams(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS user_subjects(user_id INT NOT NULL,subject_id INT NOT NULL,PRIMARY KEY(user_id,subject_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS teacher_grades(user_id INT NOT NULL,grade_id INT NOT NULL,PRIMARY KEY(user_id,grade_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(grade_id) REFERENCES grades(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS teacher_subjects(user_id INT NOT NULL,subject_id INT NOT NULL,PRIMARY KEY(user_id,subject_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE) ENGINE=InnoDB;

-- SQLAlchemy-created tables may not have server-side defaults. Normalize them
-- before repeat-safe seed inserts so an existing empty schema is supported.
UPDATE education_levels SET is_active=TRUE WHERE is_active IS NULL;
UPDATE grades SET is_active=TRUE WHERE is_active IS NULL;
UPDATE streams SET is_active=TRUE WHERE is_active IS NULL;
UPDATE grade_subjects SET is_active=TRUE WHERE is_active IS NULL;
UPDATE subjects SET is_active=TRUE WHERE is_active IS NULL;
ALTER TABLE education_levels MODIFY is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE grades MODIFY is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE streams MODIFY is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE grade_subjects MODIFY is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE subjects MODIFY is_active BOOLEAN NOT NULL DEFAULT TRUE;

INSERT INTO education_levels(code,name_en,name_ta,name_si,sort_order,is_active) VALUES
('PRIMARY','Primary','ஆரம்பக் கல்வி','ප්‍රාථමික',1,TRUE),('JUNIOR','Junior Secondary','கனிஷ்ட இடைநிலை','කනිෂ්ඨ ද්විතීයික',2,TRUE),('OL','G.C.E. O/L','க.பொ.த. சாதாரண தரம்','අ.පො.ස. සාමාන්‍ය පෙළ',3,TRUE),('AL','G.C.E. A/L','க.பொ.த. உயர்தரம்','අ.පො.ස. උසස් පෙළ',4,TRUE),('TEACHER','Teacher','ஆசிரியர்','ගුරු',5,TRUE),('UNIVERSITY','University/College','பல்கலைக்கழகம்/கல்லூரி','විශ්වවිද්‍යාලය/විද්‍යාලය',6,TRUE),('SELF','Self-Learner','சுய கற்பவர்','ස්වයං ඉගෙනුම්කරු',7,TRUE)
ON DUPLICATE KEY UPDATE name_en=VALUES(name_en),name_ta=VALUES(name_ta),name_si=VALUES(name_si),sort_order=VALUES(sort_order),is_active=TRUE;
INSERT INTO grades(level_id,code,name_en,name_ta,name_si,grade_number,sort_order,is_active)
SELECT l.id,CONCAT('GRADE_',n.n),CONCAT('Grade ',n.n),CONCAT('தரம் ',n.n),CONCAT(n.n,' ශ්‍රේණිය'),n.n,n.n,TRUE FROM education_levels l JOIN (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13)n WHERE l.code=CASE WHEN n.n<=5 THEN 'PRIMARY' WHEN n.n<=9 THEN 'JUNIOR' WHEN n.n<=11 THEN 'OL' ELSE 'AL' END ON DUPLICATE KEY UPDATE level_id=VALUES(level_id),name_en=VALUES(name_en),name_ta=VALUES(name_ta),name_si=VALUES(name_si),is_active=TRUE;
INSERT INTO grades(level_id,code,name_en,name_ta,name_si,sort_order,is_active) SELECT id,CONCAT(code,'_GENERAL'),name_en,name_ta,name_si,20,TRUE FROM education_levels WHERE code IN('TEACHER','UNIVERSITY','SELF') ON DUPLICATE KEY UPDATE name_en=VALUES(name_en),is_active=TRUE;
INSERT INTO streams(code,name_en,name_ta,name_si,sort_order,is_active) VALUES
('BIOLOGICAL_SCIENCE','Biological Science','உயிரியல் விஞ்ஞானம்','ජීව විද්‍යා',1,TRUE),('PHYSICAL_SCIENCE','Physical Science','பௌதிக விஞ்ஞானம்','භෞතික විද්‍යා',2,TRUE),('COMMERCE','Commerce','வர்த்தகம்','වාණිජ',3,TRUE),('ARTS','Arts','கலை','කලා',4,TRUE),('ENGINEERING_TECHNOLOGY','Engineering Technology','பொறியியல் தொழில்நுட்பம்','ඉංජිනේරු තාක්ෂණවේදය',5,TRUE),('BIO_SYSTEMS_TECHNOLOGY','Bio Systems Technology','உயிர் முறைமைகள் தொழில்நுட்பம்','ජෛව පද්ධති තාක්ෂණවේදය',6,TRUE),('GENERAL','General/Common Subjects','பொது பாடங்கள்','සාමාන්‍ය විෂයයන්',7,TRUE)
ON DUPLICATE KEY UPDATE name_en=VALUES(name_en),name_ta=VALUES(name_ta),name_si=VALUES(name_si),is_active=TRUE;

INSERT INTO subjects(level,stream,subject_code,name_en,name_ta,name_si,sort_order) VALUES
('PRIMARY','General','P01','First Language','முதல் மொழி','පළමු භාෂාව',1),('PRIMARY','General','P02','English','ஆங்கிலம்','ඉංග්‍රීසි',2),('PRIMARY','General','P03','Mathematics','கணிதம்','ගණිතය',3),('PRIMARY','General','P04','Environmental Studies','சுற்றாடல் கற்கைகள்','පරිසර අධ්‍යයනය',4),('PRIMARY','General','P05','Religion','சமயம்','ආගම',5),('PRIMARY','General','P06','Aesthetic Activities','அழகியல் செயற்பாடுகள்','සෞන්දර්ය ක්‍රියාකාරකම්',6),('PRIMARY','General','P07','Health and Physical Activities','சுகாதார உடற் செயற்பாடுகள்','සෞඛ්‍ය හා ශාරීරික ක්‍රියාකාරකම්',7),
('JUNIOR','General','J01','First Language','முதல் மொழி','පළමු භාෂාව',1),('JUNIOR','General','J02','English','ஆங்கிலம்','ඉංග්‍රීසි',2),('JUNIOR','General','J03','Mathematics','கணிதம்','ගණිතය',3),('JUNIOR','General','J04','Science','விஞ்ஞானம்','විද්‍යාව',4),('JUNIOR','General','J05','History','வரலாறு','ඉතිහාසය',5),('JUNIOR','General','J06','Geography','புவியியல்','භූගෝල විද්‍යාව',6),('JUNIOR','General','J07','Civic Education','குடியியல் கல்வி','පුරවැසි අධ්‍යාපනය',7),('JUNIOR','General','J08','Religion','சமயம்','ආගම',8),('JUNIOR','General','J09','Health and Physical Education','சுகாதாரமும் உடற்கல்வியும்','සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය',9),('JUNIOR','General','J10','Information and Communication Technology','தகவல் தொடர்பாடல் தொழில்நுட்பம்','තොරතුරු හා සන්නිවේදන තාක්ෂණය',10),('JUNIOR','General','J11','Second National Language','இரண்டாம் தேசிய மொழி','දෙවන ජාතික භාෂාව',11),('JUNIOR','General','J12','Art','சித்திரம்','චිත්‍ර',12),('JUNIOR','General','J13','Music','இசை','සංගීතය',13),('JUNIOR','General','J14','Dancing','நடனம்','නර්තනය',14),('JUNIOR','General','J15','Drama','நாடகம்','නාට්‍ය',15),
('OL','General','O01','First Language','முதல் மொழி','පළමු භාෂාව',1),('OL','General','O02','English','ஆங்கிலம்','ඉංග්‍රීසි',2),('OL','General','O03','Mathematics','கணிதம்','ගණිතය',3),('OL','General','O04','Science','விஞ்ஞானம்','විද්‍යාව',4),('OL','General','O05','History','வரலாறு','ඉතිහාසය',5),('OL','General','O06','Religion','சமயம்','ආගම',6),('OL','General','O07','Information and Communication Technology','தகவல் தொடர்பாடல் தொழில்நுட்பம்','තොරතුරු හා සන්නිවේදන තාක්ෂණය',7),('OL','General','O08','Business and Accounting Studies','வணிகமும் கணக்கீடும்','ව්‍යාපාර හා ගිණුම්කරණ අධ්‍යයනය',8),('OL','General','O09','Geography','புவியியல்','භූගෝල විද්‍යාව',9),('OL','General','O10','Citizenship Education','குடியுரிமைக் கல்வி','පුරවැසි අධ්‍යාපනය',10),('OL','General','O11','Health and Physical Education','சுகாதாரமும் உடற்கல்வியும்','සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය',11),('OL','General','O12','Tamil Literature','தமிழ் இலக்கியம்','දෙමළ සාහිත්‍යය',12),('OL','General','O13','Sinhala Literature','சிங்கள இலக்கியம்','සිංහල සාහිත්‍යය',13),('OL','General','O14','English Literature','ஆங்கில இலக்கியம்','ඉංග්‍රීසි සාහිත්‍යය',14),('OL','General','O15','Art','சித்திரம்','චිත්‍ර',15),('OL','General','O16','Music','இசை','සංගීතය',16),('OL','General','O17','Dancing','நடனம்','නර්තනය',17),('OL','General','O18','Drama','நாடகம்','නාට්‍ය',18),('OL','General','O19','Agriculture and Food Technology','விவசாய உணவுத் தொழில்நுட்பம்','කෘෂි හා ආහාර තාක්ෂණය',19),('OL','General','O20','Design and Construction Technology','வடிவமைப்பு கட்டுமான தொழில்நுட்பம்','නිර්මාණ හා ඉදිකිරීම් තාක්ෂණය',20),('OL','General','O21','Design and Mechanical Technology','வடிவமைப்பு இயந்திர தொழில்நுட்பம்','නිර්මාණ හා යාන්ත්‍රික තාක්ෂණය',21),('OL','General','O22','Electronic Writing and Shorthand','மின்னணு எழுத்தும் சுருக்கெழுத்தும்','ඉලෙක්ට්‍රොනික ලිවීම හා ලඝු ලේඛනය',22),('OL','General','O23','Communication and Media Studies','தொடர்பாடல் ஊடகக் கற்கைகள்','සන්නිවේදනය හා මාධ්‍ය අධ්‍යයනය',23),('OL','General','O24','Second National Language','இரண்டாம் தேசிய மொழி','දෙවන ජාතික භාෂාව',24)
ON DUPLICATE KEY UPDATE name_en=VALUES(name_en),name_ta=VALUES(name_ta),name_si=VALUES(name_si),sort_order=VALUES(sort_order),is_active=TRUE;
INSERT IGNORE INTO grade_subjects(grade_id,subject_id,medium,sort_order,is_active)
SELECT g.id,s.id,'all',s.sort_order,TRUE FROM grades g JOIN education_levels l ON l.id=g.level_id JOIN subjects s ON s.level=l.code WHERE l.code IN('PRIMARY','JUNIOR','OL');
-- Existing A/L subjects apply to both Grades 12 and 13; stream filtering remains in subject_streams.
INSERT IGNORE INTO grade_subjects(grade_id,subject_id,medium,sort_order,is_active) SELECT g.id,s.id,'all',s.sort_order,TRUE FROM grades g JOIN subjects s ON s.level='AL' WHERE g.code IN('GRADE_12','GRADE_13');
