import { useCallback,useEffect,useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import { useAuth } from "../../hooks/useAuth";
import { usePreferences } from "../../hooks/usePreferences";
import { getMyTeacherVerification,getMyTeacherVerificationDocument,submitTeacherVerification } from "../../services/api";
import Card from "../../components/Card";import Loader from "../../components/Loader";import Button from "../../components/Button";

const allowed=["application/pdf","image/jpeg","image/png"];
export default function TeacherVerification(){const{user,refreshUser}=useAuth(),{t}=usePreferences();const[application,setApplication]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[file,setFile]=useState(null);const[form,setForm]=useState({full_name:user?.name||"",qualification:"",institution_name:"",years_of_experience:"",subjects_taught:"",official_email:"",additional_information:""});
  const load=useCallback(()=>getMyTeacherVerification().then(async r=>{setApplication(r.data);if(r.data?.status==="approved")await refreshUser()}).catch(e=>toast.error(e.response?.data?.detail||t("teacher.loadFailed"))).finally(()=>setLoading(false)),[refreshUser,t]);useEffect(()=>{load()},[load]);
  const selectFile=e=>{const next=e.target.files?.[0]||null;if(next&&(!allowed.includes(next.type)||next.size>5*1024*1024)){toast.error(t("teacher.invalidFile"));e.target.value="";return setFile(null)}setFile(next)};
  const submit=async e=>{e.preventDefault();if(!file)return toast.error(t("teacher.documentRequired"));const data=new FormData();Object.entries(form).forEach(([key,value])=>data.append(key,typeof value==="string"?value.trim():value));data.append("proof",file);setSaving(true);try{const r=await submitTeacherVerification(data);setApplication(r.data);toast.success(t("teacher.submitted"))}catch(error){toast.error(error.response?.data?.detail||t("teacher.submitFailed"))}finally{setSaving(false)}};
  const viewDocument=async()=>{try{const r=await getMyTeacherVerificationDocument(application.id);const url=URL.createObjectURL(r.data);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(error){toast.error(error.response?.data?.detail||t("teacher.documentFailed"))}};
  if(loading)return <Loader/>;if(user?.role==="admin")return <Card><p>{t("teacher.studentsOnly")}</p></Card>;
  if(application?.status==="pending")return <Card className="mx-auto max-w-2xl text-center"><h1 className="page-title">{t("teacher.pendingTitle")}</h1><p className="mt-3 text-slate-500">{t("teacher.pendingMessage")}</p><button className="btn-secondary mt-5" onClick={viewDocument}>{t("teacher.viewDocument")}</button></Card>;
  if(application?.status==="approved")return <Card className="mx-auto max-w-2xl text-center"><h1 className="page-title text-emerald-600">{t("teacher.approvedTitle")}</h1><p className="mt-3 text-slate-500">{t("teacher.approvedMessage")}</p><Link className="btn-primary mt-5 inline-flex" to="/teacher/dashboard">{t("teacher.openDashboard")}</Link></Card>;
  return <div className="mx-auto max-w-2xl space-y-5"><div><h1 className="page-title">{t("teacher.applyTitle")}</h1><p className="mt-1 text-slate-500">{t("teacher.applySubtitle")}</p></div>{application?.status==="rejected"&&<Card className="border-red-200 bg-red-50 dark:border-red-900 dark:bg-red-950/30"><h2 className="font-bold text-red-700 dark:text-red-300">{t("teacher.rejectedTitle")}</h2><p className="mt-1 text-sm">{application.rejection_reason}</p><p className="mt-2 text-xs text-slate-500">{t("teacher.resubmitMessage")}</p></Card>}<Card><form onSubmit={submit} className="space-y-4">
    <label className="block text-sm font-medium">{t("teacher.qualification")}<input required minLength="2" maxLength="255" className="input-field mt-1" value={form.qualification} onChange={e=>setForm({...form,qualification:e.target.value})}/></label>
    <label className="block text-sm font-medium">{t("teacher.institution")}<input required minLength="2" maxLength="255" className="input-field mt-1" value={form.institution_name} onChange={e=>setForm({...form,institution_name:e.target.value})}/></label>
    <label className="block text-sm font-medium">{t("teacher.experience")}<input required type="number" min="0" max="70" className="input-field mt-1" value={form.years_of_experience} onChange={e=>setForm({...form,years_of_experience:e.target.value})}/></label>
    <label className="block text-sm font-medium">{t("teacher.specializations")}<input required className="input-field mt-1" placeholder={t("teacher.specializationsPlaceholder")} value={form.subjects_taught} onChange={e=>setForm({...form,subjects_taught:e.target.value})}/><span className="text-xs text-slate-500">{t("teacher.commaSeparated")}</span></label>
    <label className="block text-sm font-medium">{t("teacher.document")}<input required type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" className="input-field mt-1" onChange={selectFile}/><span className="text-xs text-slate-500">{t("teacher.documentHelp")}</span></label>
    <Button type="submit" loading={saving} className="w-full">{application?.status==="rejected"?t("teacher.resubmit"):t("teacher.submit")}</Button>
  </form></Card></div>}
