const pages = {
  about: ["About Learnfy AI", "Learnfy AI helps students and teachers learn, share educational material, and use assisted study tools. [OWNER/ORGANIZATION NAME TO BE SUPPLIED]."],
  support: ["Contact & Support", "For account, safety, or billing help contact [SUPPORT EMAIL TO BE SUPPLIED]. Do not send passwords, card details, or verification documents by ordinary email."],
  faq: ["Frequently Asked Questions", "AI results may be inaccurate and should be checked against trusted course material. Premium access is activated only after the payment provider confirms the subscription."],
  privacy: ["Privacy Policy Template", "We process account, learning, usage, moderation, and security data. Student and teacher verification documents are private and accessible only to authorized reviewers. Define a reviewed retention period at [RETENTION PERIOD]. Gemini may process submitted prompts and learning content to generate answers. Request access or deletion through [PRIVACY CONTACT]."],
  terms: ["Terms of Service Template", "Users must submit lawful educational content, respect others, and protect their accounts. AI output is assistance, not guaranteed advice. This template requires legal review before launch. Governing law and operator identity: [TO BE SUPPLIED]."],
  refunds: ["Refund Policy Template", "Subscriptions can be managed or cancelled through the billing portal and remain subject to the provider's confirmed billing state. Cancellation does not itself promise a refund. Add legally reviewed eligibility, timelines, and contact details at [REFUND RULES TO BE SUPPLIED]."],
  community: ["Community Guidelines", "Be respectful, keep discussions educational, protect personal information, and report harmful or misleading content. Reports do not automatically remove content; authorized administrators review and audit moderation actions."],
  ai: ["AI Disclaimer", "Gemini-generated explanations, summaries, quizzes, flashcards, and plans can be incomplete or incorrect. Verify important answers with teachers and trusted sources. Do not submit unnecessary sensitive information in prompts."],
  deletion: ["Account & Data Deletion Policy", "Request deletion from Settings or contact [PRIVACY CONTACT TO BE SUPPLIED]. Identity verification may be required. Define retention for security, payment, audit, and legal records at [RETENTION SCHEDULE]. Private verification documents must be removed according to that reviewed schedule."],
};
export default function TrustPage({ page }) {
  const [title, body] = pages[page] || pages.about;
  return <main className="mx-auto max-w-4xl px-5 py-14"><article className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm dark:border-slate-700 dark:bg-slate-900 md:p-12"><p className="text-sm font-bold uppercase tracking-wider text-primary-600">Legal review required</p><h1 className="mt-3 text-3xl font-black text-slate-900 dark:text-white md:text-4xl">{title}</h1><p className="mt-6 whitespace-pre-line leading-8 text-slate-600 dark:text-slate-300">{body}</p><p className="mt-8 rounded-xl bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-950/40 dark:text-amber-200">This multilingual-ready policy template is not legal advice. Supply the marked details and obtain local legal review before public launch.</p></article></main>;
}
